tiiuae/px4-firmware

ROMFS/px4fmu_common/init.d-posix/airframes/4400_ssrc_fog_x, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt, platforms/posix/cmake/sitl_target.cmake
Signed-off-by: Jari Nippula <jarix@ssrc.tii.ae>
PX4_SITL build target missing for SSRC Fog drone
ssrc_fog_x build target and airframe added into PX4_SITL
=> Add ssrc_fog_x as SITL target

ROMFS/px4fmu_common/init.d-posix/airframes/4400_ssrc_fog_x
There is something wrong with publishing sensor_combined when Multi EKF is used
This breaks receiving the sensor data to ROS via fastRTPS
Also the real drone doesn't use Multi-EKF, so it is better to disable also for simulation for us
A clear and concise description of …
=> Disable Multi EKF for 4400_ssrc_fog_x sitl

src/modules/micrortps_bridge/micrortps_client/microRTPS_client_main.cpp
This enables support for 'p:' prefix for the option value to get
current parameter value from px4 param store.
Signed-off-by: Jari Nippula <jarix@ssrc.tii.ae>
=> micrortps_client: Use px4_get_parameter_value to parse baudrate option

src/lib/parameters/flashparams/flashfs.c
Fix a potential crash caused by calling erase_sector with a null
sector_descriptor (current_sector == 0).
How was it tested? What cases were covered? Logs …
=> flashparams: Fix a null-pointer dereference crash

src/drivers/protocol_splitter/protocol_splitter.cpp
Protocol_splitter uses currently 8-bytes header, that is relatively long for short messages. Using shorted header would give better performance.
Protocol_splitter header is reduced from 8-bytes to 4-bytes. This is done by reducing the identifier magic bytes from 3 to 1, including the message type into one bit (either mavlink or rtps) in the MSB of second length byte and finally removing the reserved alignment bytes in the end of header. To compensate reduction of magic bytes and keep detection robust the last byte is used as a checksum over header (excluding the magic byte).
Considered to increase …
=> Protocol_splitter: 4-byte header with checksum

src/drivers/distance_sensor/ll40ls/LidarLiteI2C.cpp
Improve 316ccf60b "ll40ls: Don't report the measurement if peak strength is outside limits"
- Don't report invalid measurements, for which the sensor ouputs 1cm distance; these are not relevant for anything
- For "valid" measurements with distance and peak values out of range, report them with 0 quality …
=> Fix ll40ls driver further

platforms/nuttx/src/px4/stm/stm32_common/board_reset/board_reset.cpp
=> stm32_common:board_reset Fix reboot -b broke by canbootloader

boards/ssrc/saluki/src/board_config.h, platforms/nuttx/src/px4/microchip/mpfs/version/board_mcu_version.c
Implement MPFS version API.
Add support for PX4GUID which is generated from
PX4_SOC_ARCH_ID_MPFS and device serial number.
Read HW version from GPIO pins.
=> Board identity support for MPFS / Saluki

src/modules/ekf2/EKF2.cpp, src/modules/ekf2/EKF2.hpp
For historical reasons, there is a check in EKF2 to only publish global
position if it has moved for 1mm.
This is no longer necessary, and also this if doesn't save any cpu cycles
in real conditions where GPS errors are always much bigger that this.
When using simulated or fake GPS, based on some other positioning
system, the GPS coordinate input can be very accurate due to quantization
or true accuracy. In this case this check bites and perfectly valid position
doesn't get published.
Just removed this if.
A …
=> EKF2: Always publish global position

ROMFS/px4fmu_common/init.d/airframes/4400_ssrc_fog_x
Enable safety switch by default when ssrc_fog_x airframe is selected
=> Fix io safety

ssrc_config/indoor_lighthouse/config.txt
This makes indoor flight with waypoints very close to each other a bit smoother
Adding these parameters only for the config.txt file on sdcard for indoors testing; this needs to be re-evaluated for high-speed outdoor flights. Most probably we need to do something with the flight task code itself to navigate properly with this kind of set of waypoints very close to each other
=> ssrc_configs: Fine tune MPC_JERK_AUTO and MPC_ACC_HOR for indoor flight

ssrc_config/HIL/config.txt, ssrc_config/HIL/spawn_ssrc_hil_drone.sh
Enable HITL support for ssrc_fog_x drone model.
Tools/sitl_gazebo contains fixed jinja script and ssrc_fog_x model to support dynamic spawning of HITL simulation.
New ssrc_config file created for HITL case and script to spawn ssrc_fog_x model with HITL setup into simulation world. Script configures model to connect pixhawk4/PX4 via serial port: /dev/ttyUSB0 -> TELEM2
=> Dynamic HITL enabling support

src/lib/parameters/param_translation.cpp
Remove the SPI address reset to 0 on import.
Zeroing causes ID mismatch when there are multiple sensors of the same type on the same bus,
because only difference between device IDs is device_id.devid_s.address.
=> Fix parameter translation

Tools/px4moduledoc/srcparser.py, platforms/common/i2c_spi_buses.cpp, platforms/common/include/px4_platform_common/i2c_spi_buses.h, platforms/common/include/px4_platform_common/spi.h, platforms/common/module.cpp, platforms/common/spi.cpp
Make possible to define chip-select pin for internal SPI.
By defining chip-select, it's possible to start specific SPI device.
This allows to have several same type of sensors on the same bus with different orientation.
Enables second ICM-42688-P
=> SPIbus fix

ROMFS/px4fmu_common/init.d/airframes/4400_ssrc_fog_x, ssrc_config/indoor_lighthouse/config.txt
- TELEM2 link if the  high speed link to MC
- TELEM1 is for leds
- Removed the LED settings from "indoor microsd config", these are in defaults already
How was it …
=> 4400_ssrc_fog_x: Change mission computer link from TELEM1 to TELEM2

platforms/nuttx/src/px4/common/cdc_acm_check.cpp
This is already in px4 master, syncinc to our branch
=> Fix invalid comparisons in cdc_acm_check

platforms/nuttx/src/px4/microchip/mpfs/board_reset/board_reset.cpp
On normal reboot, just start over via reset vector
=> mpfs/board_reset: Only issue full SoC reset when entering bootloader

ROMFS/px4fmu_common/init.d-posix/airframes/4400_ssrc_fog_x
PX4_SITL: Change logging mode to start and stop loggign on arming/disarming instead of start logging on bootup.
This prevents to fill-up disk space in simulation where drone is just spawned into simulation but not used.
=> PX4_SITL: Start logging on arming instead of from bootup

ROMFS/px4fmu_common/init.d/airframes/4400_ssrc_fog_x
In the lab we could see that some messages were missing from topic _fmu/mission_result/out_.
After we increased baudrate from 1Mb to 2Mb we could see that the amount of missing messages was considerably smaller and we were able to make bigger amount of successful flights.
=> Increase UART baudrate after successful tests with 2Mb

packaging/px4_update_fw.sh
This update is needed after bootloader was changed to use TELEM2 port and 2Mb baudrate.
=> Use the same baudrate as new bootloader

packaging/build_px4fwupdater.sh
px_uploader.py script was missing from px4fwupdater debian package generated by new CI build scripts.
=> Add missing px_uploader.py into px4fwupdater package

src/modules/logger/log_writer_file.cpp
If the board supports encrypting logfiles, but the parameter SDCARD_ALGORITHM is set to NONE,
the log should be written to the sdcard in plaintext format. This fixes a bug which caused
logger to hang in mutex instead.
=> Fix sdcard logging when crypto is used but algorithm is set to NONE

src/drivers/protocol_splitter/protocol_splitter.cpp
Always make room in the receive buffer for reading out data. Otherwise the
client may end up in busyloop, when there is no valid data in the buffer to read.
The poll may still return 1, in case there is new data in the actual input
device (socket or uart buffer).
The problem is easy to re-produce by writing random (garbage) data to mavlink through protocol splitter.
=> Fix the protocol_splitter receive buffer getting full case

ssrc_config/indoor_lighthouse/config.txt
This disables the magnetometer by default in the indoor configuration
file.
This resolves the toilet bowl effect, where the magnetometer is
conflicting with data from the motion capture system.
Co-authored-by: Humaid <humaid@ssrc.tii.ae>
Co-authored-by: Pedro <pedro@ssrc.tii.ae>
=>  indoor config.txt: disable magnetometer 

platforms/nuttx/cmake/Platform/Generic-riscv64-unknown-elf-gcc-rv64gc.cmake, src/drivers/sw_crypto/crypto.c
This is a set of two unrelated patches, one fixes crypto library in the way which saves ~30KB for saluki bootloader.
The second one removes risc-v relaxations; these were the source of all the weird GP related linking problems
=> Riscv compilation fixes

ssrc_config/indoor_lighthouse/config.txt
I'm adding this PR in order to have the flight modes pre-defined and also the mode channel and kill switch channel.
I believe that leaving the user to set this up is unnecessary, considering this is the same for all the drones we use.
That way, the user would only need to deal with Radio and Sensors Calibration after provisioning, because these are the only parameters that might change from drone to drone.
=> Add default flight models and kill switch channel

ROMFS/px4fmu_common/init.d-posix/airframes/4400_ssrc_fog_x
Fixing the typo in SITL logger mode change
Original change was done to prevent SW simulation container to run out of disk quota while just keeping simulation running without flying the drone.
=> Fix typo in SITL logger mode change

ROMFS/px4fmu_common/init.d-posix/CMakeLists.txt, ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator, ROMFS/px4fmu_common/init.d-posix/rcS.sim_tcp_server, packaging/entrypoint.sh, src/modules/simulator/simulator.cpp, src/modules/simulator/simulator.h, src/modules/simulator/simulator_mavlink.cpp
PX4_SITL simulator to support TCP Server mode (set default)
sitl_gazebo mavlink plugin improvements
- Support TCP client mode
- TCP/UDP message sending and receiving moved to separate threads. Messages transferred between main thread and sender/receiver threads via message queues
=> DP-2269 gazebo mavlink plugin receiving in separate thread

packaging/entrypoint.sh
Add **PX4_SIM_USE_TCP_SERVER** environment variable when running px4_sitl container to enable TCP server connection for gazebo mavlink plugin.
=> px4_sitl: entrypoint check PX4_SIM_USE_TCP_SERVER env variable to

boards/px4/fmu-v5x/init/rc.board_mavlink
This enables ethernet, and corrects usb functionality for saluki bootloader (can be flashed now via USB / ttyACM0)
It also fixes one bug in enabling ethernet on px4 fmuv5x
=> Enable eth on saluki

Tools/px_uploader.Dockerfile, Tools/px_uploader.py
In addition to send "reset to booloader" command via uart, the message shall be sent via ethernet in case there is no mavlink interface up&running in the uart.
=> px4_uploader: send reset command also via eth

ROMFS/px4fmu_common/init.d/airframes/4400_ssrc_fog_x
FOG drones switched to use ethernet in mission computer side for FC<->MC connection. This requires PX4 side RTPS_MAV_CONFIG param to be cleared to enable ethernet for MC connection.
=> Disable RTPS_MAV UART config to enable ethernet connection

boards/ssrc/icicle/nuttx-config/scripts/bootloader_script.ld, boards/ssrc/icicle/nuttx-config/scripts/script.ld, boards/ssrc/icicle/src/toc.c
There is no need to force object linkage manually, if the correct
section is used.
Also fix typo in toc.c, the image starts from __start, not _vectors
(copy & paste artifact from ARM).
=> boards/ssrc/icicle: Clean up linker scripts

platforms/nuttx/NuttX/CMakeLists.txt
Use CONFIG_ARCH instead of arm
=> platforms/nuttx: Fix hard coded path for karch library

src/lib/mixer_module/CMakeLists.txt
The module has a hard dependency on mixer library, so link them together
=> mixer_module: Fix linking of mixer_module

src/modules/simulator/simulator.h, src/modules/simulator/simulator_mavlink.cpp
Simulator generates new device_id value for each new gps id detected
from received hil_gps message. Generated device_id is not stored
but latter sensor_gps messages for the same gps device has device_id
value zero. This patch stores the generated device_id and use the
value in next messages.
=> Store gps device_id generated from gps id of hil_gps message

boards/ssrc/icicle/src/init.c
The board should implement this dummy function, don't know why it didn't
=> boards/icicle: Add board_read_VBUS_state

platforms/nuttx/CMakeLists.txt
The comment is right, it is not needed -> get rid of it
=> Remove px4_work_queue from the kernel side LD command

.github/workflows/tiiuae-pixhawk.yaml, .gitmodules
**What is this PR for**
Enable cicd on ml_develop branch to push generated builds and docker image to ssrcdevops artifactory.  
Reconfigured existing cicd code to use ssrcdevops jfrog container registry and generic repositories. Enabled manual trigger on the workflow. Added required github secrets. Edited gitmodules for directly referring the private repository using token. 
Forked the repository and tested code on second account. Added required github secrets. Edited gitmodules for directly referring the private repository using token. Created PR.
=> Enable cicd on ml_develop branch

ROMFS/px4fmu_common/init.d/airframes/4400_ssrc_fog_x
Also remove the multi-ekf parameter settings, just use the defaults
=> 4400_ssrc_fog_x Set range finder as default HGT source

platforms/nuttx/src/bootloader/microchip/mpfs/main.c, platforms/nuttx/src/px4/common/nuttx_random.c, src/drivers/pfsoc_crypto/CMakeLists.txt, src/drivers/pfsoc_crypto/Kconfig, src/drivers/pfsoc_crypto/crypto.c, src/drivers/pfsoc_crypto/crypto_backend_definitions.h, src/drivers/stub_keystore/Kconfig
This is a stub implementation to start creating driver for PF SOC crypto module.
I left monocypher signature check in this module still so that we can take it into use in bootloader already.
=> Create pf crypto backend stub

boards/px4/fmu-v5/src/board_config.h, platforms/common/CMakeLists.txt, platforms/common/board_common.c, platforms/common/include/px4_platform_common/board_common.h, platforms/nuttx/src/px4/common/board_ioctl.c, platforms/nuttx/src/px4/common/include/px4_platform/board_ctrl.h, platforms/nuttx/src/px4/common/px4_protected_layers.cmake, platforms/nuttx/src/px4/common/usr_board_ctrl.c
Move logic implemented in the header files to source files, this way
it will be simpler to define which is compiled to kernel space and
which to user space
Also allows to remove some headers that pull in half the universe
from the board definitions (which should just be pin definitions and
no functionality)
=> board_ctrl: Clean up usage of VBUS, nARMED from user/kernelspace

platforms/nuttx/src/px4/common/hrt_ioctl.c, platforms/nuttx/src/px4/common/px4_init.cpp, platforms/nuttx/src/px4/common/px4_protected_layers.cmake, platforms/nuttx/src/px4/stm/stm32_common/hrt/hrt.c, src/drivers/drv_hrt.h
The HRT ioctl is common code, so move it out of chip specific code
=> hrt_ioctl: Move common code under /common folder

packaging/Dockerfile.sitl
Update px4_sitl container (used in simulation) to use fog-ros-baseimage to get correct fastdds version in use.
=> Use fog ros baseimage for sitl

ROMFS/px4fmu_common/init.d/airframes/4400_ssrc_fog_x
Disable unused MAV_0 and MAV_2 by default for airframe 4400
=> Disable MAV_0 and MAV_2 by default for airframe 4400

src/modules/gyro_fft/GyroFFT.cpp
The original code was resetting only the parameter, but it wasn't updating _rfft_q15 attributes, so the changes were not really acting as it should.
=> Fix GyroFFT default fallback.

boards/ssrc/icicle/nuttx-config/scripts/bootloader_script.ld, platforms/nuttx/CMakeLists.txt
Depends on NuttX change https://github.com/tiiuae/nuttx/pull/51
=> boards/icicle: Remove ddrstorage section from bootloader

ROMFS/px4fmu_common/init.d/airframes/4400_ssrc_fog_x, src/drivers/gps/module.yaml
We had earlier an own startup parameter -s for enabling satellite info. Now this parameter is unrecognized and breaks the gps start. So revert the earlier change.
PX4 has changed this into parameter "GPS_SAT_INFO", which we can now set enabled by default
=> Fix gps start

ROMFS/px4fmu_common/init.d/airframes/4400_ssrc_fog_x
Also remove the default BAT1_V_LOAD_DROP and use the same default value as for
pixhawk 5x
=> Update boards/ssrc/saluki-v1 submodule for power brick configuration

platforms/nuttx/src/bootloader/microchip/mpfs/main.c
Set the px4 entry point run-time, also, update the nuttx submodule that brings support for this change.
=> Px4 run time entry point

platforms/nuttx/src/bootloader/microchip/mpfs/main.c
If the SD card is not mounted, the bootloader will softlock in
flash_func_erase_sector() where loading_status is tested, and if
the value is not FAIL/DONE the bootloader_main process will sleep
forever.
This happens because the task that was supposed to wake it up (loader_main)
has already exited because it had no work to be done due to the SD card
missing.
=> mpfs/bootloader: Fix bootloader softlock if SD card is missing

platforms/nuttx/src/px4/common/tasks.cpp
Use libc procedures to exit, kill and ask for process name, instead of fiddling around with the tcb directly.
=> nuttx/tasks.cpp: Use libc procedures to exit, kill and ask for process name

boards/px4/fmu-v5x/init/rc.board_mavlink
Mavlink issues with latest px4 firmware. Need to test whether this additional mavlink instance causes the connection breaks.
=> Test disable additional mavlink

src/drivers/imu/invensense/icm42688p/ICM42688P.cpp
This prevents accidental misconfiguration via I2C if there are
multiple SPI devices on the same bus. The device may hear it's i2c address
and write some register, while there is data transfer ongoing with another
device.
A clear and concise description of alternative …
=> Disable I2C interface in ICM42688P sensor when it is initialized

boards/px4/fmu-v5/nuttx-config/scripts/script.ld, boards/px4/fmu-v5/nuttx-config/scripts/toc.ld, boards/px4/fmu-v5x/nuttx-config/scripts/script.ld, boards/px4/fmu-v5x/nuttx-config/scripts/toc.ld
- The vector table needs to be aligned correctly, depends on the amount of interrupts. 4K should be enough for this target.
- Padd the firmware to the correct size, the signature must start at a 4B alignment.
- The firmware end address needs to be aligned as well, because the calculated signature size is the firmware size + the additional padding
=> boards/fmuv5/x: Fix multiple alignment issues

platforms/common/include/px4_platform_common/atomic.h
fetch_add/sub were not really inc/dec for the __atomic_always_lock_free == true branch. This fixes them so that the arg "num" is actually used.
=> px4_platform_common/atomic.h: fetch_add/sub were really fetch_inc/dec

src/include/visibility.h
The syscall lookup table contains poisoned xxenv() procedures and causes a build error. The file is included via a massive header that includes almost everything in /arch/risc-v/ etc (riscv_internal.h). This was already fixed once, and, tbh, suppressing the poison error is the only way to get this to work reliably.
=> Fix CONFIG_BUILD_PROTECTED after NuttX update

src/drivers/pwm_esc/pwm_esc.cpp
task_delete() API is not always available, so forward the call to px4_task_delete() which knows what to do.
=> pwm_esc.cpp: Replace direct call to task_delete()

platforms/common/include/px4_platform_common/atomic_from_isr.h, src/drivers/imu/analog_devices/adis16448/ADIS16448.hpp, src/drivers/imu/analog_devices/adis16470/ADIS16470.hpp, src/drivers/imu/bosch/bmi055/BMI055.hpp, src/drivers/imu/bosch/bmi088/BMI088.hpp, src/drivers/imu/bosch/bmi088_i2c/BMI088.hpp, src/drivers/imu/invensense/icm20602/ICM20602.hpp, src/drivers/imu/invensense/icm20608g/ICM20608G.hpp, src/drivers/imu/invensense/icm20649/ICM20649.hpp, src/drivers/imu/invensense/icm20689/ICM20689.hpp, src/drivers/imu/invensense/icm20948/ICM20948.hpp, src/drivers/imu/invensense/icm40609d/ICM40609D.hpp, src/drivers/imu/invensense/icm42605/ICM42605.hpp, src/drivers/imu/invensense/icm42670p/ICM42670P.hpp, src/drivers/imu/invensense/icm42688p/ICM42688P.hpp, src/drivers/imu/invensense/mpu6000/MPU6000.hpp, src/drivers/imu/invensense/mpu6500/MPU6500.hpp, src/drivers/imu/invensense/mpu9250/MPU9250.hpp, src/drivers/imu/invensense/mpu9250/MPU9250_I2C.hpp
Use IRQ locking only when the atomic access is performed from IRQs
(part 2)
=> px4_platform_common/atomic.h: Use IRQ locks only when REALLY needed

platforms/nuttx/src/px4/common/CMakeLists.txt
This clearly belongs to user space, only
=> cdc_acm_check: Remove it from KERNEL_SRCS

ROMFS/px4fmu_common/init.d/airframes/4401_ssrc_fog_x_tmotor, ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt
Create initial T-Motor M690B airframe by cloning the SSRC holybro X500 configuration
The T-Motor power management HW does not provide the I2C output that Pixhawk 5X needs for current sensing. Create a new airframe config that specifies the correct value for the INA226_SHUNT parameter. Add airframe to 'CMakeLists.txt'.
=> T-Motor M690B airframe

src/modules/microdds_client/microdds_client.cpp
Try to start 5 times in case creation of entities in agent side fails. This prevent microdds_client to exit in case agent is restarting in critical time while connection is just about to happen.
=> microdds client crash fix

src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/module.yaml
Add MAV_x_REMOTE_IPn params to define partner IP for mavlink instance.
param is used when MAV_x_CONFIG is 1000 (UDP mavlink)
Support for '-i <x>' flag added to mavlink start command. It reads IP address from MAV_<x>_REMOTE_IPn params.
e.g. mavlink start -i 2  => read partner ip address from MAV_2_REMOTE_IP0..3
=> Add mavlink ip address params

platforms/nuttx/src/px4/common/hrt_ioctl.c, platforms/nuttx/src/px4/common/usr_hrt.cpp, src/drivers/drv_hrt.h
- Allocate a separate wait semaphore for each process (one in PROTECTED_BUILD). Allocate the semaphore in "REGISTER" ioctl, free it in "UNREGISTER" if process exits
- Duplicate the user side call events to kernel memory to make them accessible by kernel at all times. Keep track of the allocated items in "freelist" queue
- Replace fixed size callout queue with an "inflight" queue
=> Fix usr_hrt to work also in CONFIG_BUILD_KERNEL

platforms/nuttx/src/px4/common/px4_protected_layers.cmake, platforms/nuttx/src/px4/common/px4_userspace_init.cpp, src/systemcmds/mtd/Kconfig
- Remove mtd, it can't be used from userspace anyway
- Initialize logger, no idea why this was not done before
=> px4/userspace: Minor fixes for the px4 userspace

platforms/nuttx/src/px4/common/board_ioctl.c
lib/builtin is not available if CONFIG_BUILD_KERNEL=y (the K-configurator disables the CONFIG_BUILTIN flag)
argv[0] passes the full path to the process to be launched, but the builtins list only contains the name, thus, use the base name
to launch kernel modules
=> launch_kmod: Small adjustments to code in preparation for CONFIG_BUILD_KERNEL

platforms/nuttx/src/px4/common/px4_protected_layers.cmake
Do not link the soft float math library, it is not needed for anything and it confuses the linker which does relocations to the FP instructions
=> nuttx/protected_build: Fix protected build linkage

platforms/nuttx/src/px4/common/hrt_ioctl.c
error: cast increases required alignment of target type [-Werror=cast-align]
The compiler is just dumb, the alignment does not even change.
=> hrt_ioctl: Fix compiler warning about alignment requirement

src/modules/commander/esc_calibration.cpp
The actuator test is published for each motor in a row. If the orb queue size is too small, messages are lost and not received in mixer_module.
=> esc_calibration: Publish actuator_test with large enough queue size

platforms/nuttx/src/bootloader/microchip/mpfs/CMakeLists.txt, platforms/nuttx/src/bootloader/microchip/mpfs/main.c
Fix for bug "DP-4485:  Saluki bootloader does not show a version identifier"
Git commit information added
-
-
-
=> DP-4485: Git commit info is printed out in the bootloader

platforms/nuttx/src/bootloader/microchip/mpfs/main.c
This fixes 2 issues:
- Resetting the board with debugger doesn't get stuck any more
- After flashing the old info from TOC is not used in attempt to boot the image right away
I tried just resetting the board after successful flashing. This has the problem that you'd need to store the information about reset after flashing somewhere, otherwise it is indistinguishable from the sw reset from px4 (reboot -b), which needs to stay in bl.
STM boards have some freely usable registers in RTC block (which is separately powered and keep the contents over power cuts as well), which are used to store the information about the last known state. We don't have that atm. l2lim is not usable for that because it seems to loose content at reset.
After flashing it must boot right away, otherwise the flashing …
=> Fix bl logic

ROMFS/px4fmu_common/init.d/airframes/4400_ssrc_fog_x
1. Changed filter configuration to solve vibration problem when using lighter x500 configuration without MC and rplidar.
2.Added PWM_MAIN_MIN* values of 1050
=> Changed filter config to work with saluki single soc x500 frame

src/modules/microdds_client/microdds_client.cpp
datawriters were not recreated in case of reconnection to agent. Pub&Sub instances are cleared after connection lost is detected, so they are forced to be recreated when connection is regained.
=> microdds_client: cleanup pub&sub instances after connection lost

platforms/nuttx/src/px4/common/hrt_ioctl.c
The HRT driver was not storing the callback function or argument
=> Fix HRT for protected/kernel builds

ROMFS/px4fmu_common/init.d/rcS
This is done in init.d/rcS because interface does not exist before rptun is up.
Signed-off-by: Jani Paalijarvi <jani.paalijarvi@unikie.com>
=> Set IPv4 address for RPMSG network interface

platforms/nuttx/src/px4/common/hrt_ioctl.c, platforms/nuttx/src/px4/common/usr_hrt.cpp, platforms/nuttx/src/px4/microchip/mpfs/include/px4_arch/micro_hal.h, src/drivers/drv_hrt.h
Instead of using a const value for USRIO_START, which fails when dynamic linking is used (i.e. CONFIG_BUILD_KERNEL), obtain the location of MTIME via syscall to the kernel side HRT.
Overload HRT_ABSOLUTE_TIME ioctl to do this, as the old way becomes unnecessary. There is a compatibility break here but should not matter.
=> usr_hrt: Obtain location of MTIME via syscall

ROMFS/px4fmu_common/init.d/airframes/4400_ssrc_fog_x, ROMFS/px4fmu_common/init.d/airframes/4401_ssrc_fog_x_tmotor
To make PWM_OUT_SIM & mixer to generate actuator_output messages, the HIL_ACT_FUNCx params need to be set to define which actuator function is used in which HIL actuator.
=> airframe 4400 & 4401: define HIL_ACT_FUNCx params

.gitmodules, clone_public.sh
Current method of including pf_crypto into build by cloning it by makefile is not good because there is no control over the module version. By cloning master head on build time breaks the source code consistency => particular commit of px4-firmware does not contain known source code.
To fix this:
1. Added pf_crypto as submodule to px4-firmware
2. Link pf_crypto submodule path to boards/ssrc/saluki-v2/include/crypto and
boards/ssrc/saluki-v2/nuttx-config/src/crypto directories to make it compiled. 
3. Modified nuttx/arch/risc-v/src/mpfs/crypto.defs to use existing submodule instead of cloning another.
=> Add pf_crypto as submodule

platforms/nuttx/CMakeLists.txt
Makes it a bit simpler to select correct linker script(s) for each build type.
=> nuttx/CMakeLists: Add linker script selector

platforms/nuttx/CMakeLists.txt
Streams have been moved to user space, so do not need to link nuttx_sched into nuttx_c any longer.
=> nuttx/build: nxsched_get_streams no longer exists in NuttX

ROMFS/px4fmu_common/init.d/rcS
Start microdds_client after prnet is up & running
Set ip addresses in the beginning of rcS to avoid to spreading hardcoded address values in several scripts
=> Microdds wait rptun

.github/workflows/tiiuae-sitl.yaml
SITL binaries were still tried to be uploaded into old artifactory, that does not exist anymore. Fixed to use new cloud artifactory.
=> Push sitl builds to new cloud artifactory

src/drivers/pwm_esc/pwm_esc.cpp
Setting duty cycle as 0 on initialization phase in not allowed.
The value has to be something from 1 to 65535.
With 0 CorePWM FPGA block generates square wave until
the real pwm values are set after the system init has been done.
=> Fix motor spinning on reboot

ROMFS/px4fmu_common/init.d/rcS, src/systemcmds/netconfig/Kconfig, src/systemcmds/netconfig/netconfig.cpp
This uses "netconfig" app, which performs static network configuration, for all build types (default, amp).
For default builds, the PX4 IP is set to 192.168.200.100 + MAV_SYS_ID . For AMP builds, it is set to 192.168.201.101.
The IP is adjustable also in AMP builds using MAV_SYS_ID, but there is no need for that; normally MAV_SYS_ID is always 1.
=> Harmonize network start 

packaging/build_px4fw.sh
This adds own R&D test security keys for saluki-pi. saluki-v1 and saluki-v2 still use the same keys, but the images cannot be mixed by accident, as because of different DRAM the SW won't boot anyhow
=> Add own test keys for ssrc own HW targets

platforms/nuttx/src/px4/common/usr_hrt.cpp
Instead of starting the worker when a process is created, start it when a call to a hrt service happens. This drops ~30 unnecessary threads from the system, as most user processes use hrt only to obtain the system time.
=> usr_hrt: Start the worker thread only if it is needed

.github/workflows/tiiuae-pixhawk-and-saluki.yaml
Prints direct links to px4 binaries on github action step summary page so it is easier to find generated packages
=> DP-5676 print artifactory links to github step summary

boards/px4/fmu-v5x/init/rc.board_sensors
Fix for internal magnetometer (bmm150) driver not being loaded on the 02 variant of the fmu-v5x board
=> Enabled bmm150 driver for the other half of v5x models

ROMFS/px4fmu_common/init.d/50005_ssrc_scout_mini_rover, ROMFS/px4fmu_common/init.d/airframes/50005_ssrc_scout_mini_rover, ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt, ROMFS/px4fmu_common/init.d/rc.rover_apps, msg/CMakeLists.txt, msg/RoverStatus.msg, platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp, src/drivers/rover_interface/CMakeLists.txt, src/drivers/rover_interface/Kconfig, src/drivers/rover_interface/RoverInterface.cpp, src/drivers/rover_interface/RoverInterface.hpp, src/drivers/rover_interface/rover_interface_params.c, src/drivers/rover_interface/scout_sdk/CMakeLists.txt, src/drivers/rover_interface/scout_sdk/include/scout_sdk/CAN/SocketCAN.hpp, src/drivers/rover_interface/scout_sdk/include/scout_sdk/CAN/can_frame.h, src/drivers/rover_interface/scout_sdk/include/scout_sdk/ScoutRobot.hpp, src/drivers/rover_interface/scout_sdk/include/scout_sdk/Utilities.hpp, src/drivers/rover_interface/scout_sdk/include/scout_sdk/agilex_protocol/agilex_message.h, src/drivers/rover_interface/scout_sdk/include/scout_sdk/agilex_protocol/agilex_msg_parser_v2.h, src/drivers/rover_interface/scout_sdk/include/scout_sdk/agilex_protocol/agilex_protocol_v2.h, src/drivers/rover_interface/scout_sdk/include/scout_sdk/agilex_protocol/agilex_protocol_v2_parser.hpp, src/drivers/rover_interface/scout_sdk/include/scout_sdk/agilex_protocol/agilex_types.h, src/drivers/rover_interface/scout_sdk/src/CAN/SocketCAN.cpp, src/drivers/rover_interface/scout_sdk/src/ScoutRobot.cpp, src/drivers/rover_interface/scout_sdk/src/Utilities.cpp, src/drivers/rover_interface/scout_sdk/src/agilex_protocol/agilex_msg_parser_v2.c, src/drivers/rover_interface/scout_sdk/src/agilex_protocol/agilex_protocol_v2_parser.cpp
Add rover interface CAN driver. 
Currently only **AgileX Scout Mini** rover and protocol V2 is supported.
This driver is a high level CAN driver that interfaces with the socketCAN iface expose by the low level can driver.
It takes `actuator_control` msg from `rover_pos_control` module and forward that to the rover.
It listens to rover status and publish the uorb topic `rover_status`
**ROS2 (fognav)** --> trajectory_setpoint --> **PX4 (rover_pos_control)** --> actuator_controls_0 --> **PX4 (Rover Interface CAN Driver)** --> **Nuttx (canfd driver)** --> CAN Steering & Throttle Msg --> **Rover**
=> Rover interface CAN driver

platforms/nuttx/src/bootloader/microchip/mpfs/main.c
Composite needs to be initialized also in case there are no partitions on the eMMC
=> mpfs_bootloader: Fix usb composite initialization on empty eMMC

ROMFS/px4fmu_common/init.d/rc.logging
Configure logger to use mavlink logging only in case SDCARD not available/accessible
=> Select mavlink logging only if there is no SD card available

ROMFS/px4fmu_common/init.d/airframes/4400_ssrc_fog_x, src/drivers/uavcan/uavcan_main.hpp
- Add missing UAVCAN EC functions for 4 ESCs
- Increase handling rate due to double traffic with 2x CAN
- Decrease param request update rate to avoid spike on CAN traffic which could lead to erroneous frames when QGC is open
=> Changes in UAVCAN for 2x CAN support

platforms/nuttx/src/bootloader/microchip/mpfs/main.c
Trace UART is messed up sometimes if PX4 is started before bootloader has printed "Jump to Hart.."
=> bootloader: Remove "Jump to" alerts

.github/workflows/tiiuae-pixhawk-and-saluki.yaml
Currently all build targets are cancelled if one target fails to compile. With this change the build continues on remaining targets.
=> DP-5698 compile remaining targets even if one fails

.github/workflows/tiiuae-pixhawk-and-saluki.yaml
The Saluki v1 is not directly a supported platform anymore. We will move that work to maintenance → therefore for the new builds, we will disable the automatic new builds for v1. https://ssrc.atlassian.net/browse/DP-5996
=> Disable github builds for Saluki v1

ssrc_config/config_hitl_eth.txt
Because Gazebo provides only one IMU sensor data stream, the ekf2 shall wait for only one IMU instance.
=> Disable ekf2 multi-imu for HITL mode

ROMFS/px4fmu_common/init.d/rcS, platforms/nuttx/src/px4/common/cdc_acm_check.cpp, src/modules/cdcacm/CMakeLists.txt, src/modules/cdcacm/Kconfig, src/modules/cdcacm/cdcacm.cpp, src/modules/cdcacm/cdcacm.hpp
The code that checks for CDC ACM connection needs to be an actual process (module) as:
- It cannot run inside the NuttX kernel, it must be capable of starting mavlink
- It cannot run inside "the userspace" either, as with CONFIG_BUILD_KERNEL there are several "userspaces" / processes.
Do it by:
- Forklifting sercon_main() and serdis_main() from libapps, the reason is that with kernel build the symbols are NOT packed into libapps and thus are inaccessible.
- Create wrapper for builtin_exec() that can do file exec via posix_spawn()
=> cdc_acm_check: Make cdc_acm_check into its own module

src/drivers/uavcan/actuators/esc.cpp
On UAVCAN drone, sometimes, due to randomness in installation, the motor spinning direction is reverted thus require reversed current and voltage from ESC. This is needed so that only the absolute current value is passed to PX4 system, preventing trigger of esc current < 0 warning
=> UAVCAN: use esc current absolute value

src/drivers/rover_interface/RoverInterface.cpp, src/drivers/rover_interface/RoverInterface.hpp, src/drivers/rover_interface/rover_interface_params.c, src/drivers/rover_interface/scout_sdk/include/scout_sdk/CAN/SocketCAN.hpp, src/drivers/rover_interface/scout_sdk/include/scout_sdk/ScoutRobot.hpp, src/drivers/rover_interface/scout_sdk/include/scout_sdk/Utilities.hpp, src/drivers/rover_interface/scout_sdk/src/CAN/SocketCAN.cpp, src/drivers/rover_interface/scout_sdk/src/ScoutRobot.cpp, src/drivers/rover_interface/scout_sdk/src/Utilities.cpp
Set CAN bitrate from rover interface driver to 500kbit/s from default 1Mbit/s
The rover interface bitrate is configuratble as a PX4 parameter
=> rover_interface: add support for runtime bitrate setting

platforms/nuttx/src/bootloader/microchip/mpfs/main.c
This relocates the OpenSBI from eNVM into L2 zero device.
Hart0 should relocate the OpenSBI into L2 zero device.
A simple function done in asm in order to keep it small
Use memcpy etc
=> main.c: relocate OpenSBI into from eNVM

src/drivers/uavcan/uavcan_main.cpp
Suppress benign ERR msgs during UAVCAN node parameter retrieval to DEBUG since param fetching has retrial if there is error retrieving some.
=> uavcan: change err msg to debug for param get/set

build_sitl.sh, packaging/Dockerfile.sitl
The tii-px4-sitl package is missing the libignition-transport8-dev package, resulting in error like below. Not sure why it was disabled in the first place. 
```
px4: error while loading shared libraries: libignition-transport8.so.8: cannot open shared object file: No such file or directory
```
- Reenable commented out libignition-transport8-dev package. Tested on a locally built image, it worked OK after the change.
- Additionally updated the baseimage for the image, so it uses tag v2.1.0.
=> Reenable installing libignition-transport8-dev pkg in sitl image

src/include/containers/BlockingQueue.hpp
Popping did not remove old entry from the queue, resulting in duplicates when popping again from an empty queue (the same value is returned again).
Happens every time if queue size is 1, and multiple consecutive pops are performed without anyone pushing to the queue.
=> blockingqueue.hpp: remove entry from list when popping

ROMFS/px4fmu_common/init.d/airframes/4401_ssrc_fog_x_tmotor
T-motor M690 airframe (4401) had high frequency oscillations during test flight. By setting K gains for roll and pitch rate to 0.4 reduces the oscillations.
Analysis for default parameters: https://px4-flight-review.ssrc.fi/plot_app?log=e097664b-c33c-4ae1-9fb0-76329603cf3e
Analysis for modified parameters: https://px4-flight-review.ssrc.fi/plot_app?log=69b49fc4-0d12-4c16-8693-c7d49fe0fb52
=> pid tuning to avoid high frequency oscillations

src/include/containers/BlockingQueue.hpp
Apparently the initial fix of returning NULL if queue is empty is wrong, the queue should block until there is something in it.
px4_sem_wait can be interrupted by signal, thus need to loop until the semaphore is actually obtained.
=> blockingqueue.hpp: Block reading from queue until someone actually posts into it

platforms/common/shutdown.cpp, platforms/nuttx/src/px4/microchip/mpfs/board_reset/board_reset.cpp
Fixes reboot command by:
- Start user workqueue thread in kernel mode by "lazy init"
- Provide hartid in a0 for __start() as required
=> systemcmds/reboot: Fix reboot command for kernel mode

ROMFS/px4fmu_common/init.d/airframes/50005_ssrc_scout_mini_rover, src/drivers/rover_interface/RoverInterface.cpp, src/drivers/rover_interface/RoverInterface.hpp, src/drivers/rover_interface/rover_interface_params.c
- Allow configurable manual control speed of up to Scout Mini maximum speed of 3m/s
- Configure battery cell count and voltage range
- Configure more tolerant EKF2 GPS errors
- Add support for Bunker and Bunker Mini rover
Tested on UGV2 with Saluki v2 and X86
=> UGV improvements

ROMFS/px4fmu_common/init.d/rc.rover_apps, src/drivers/rover_interface/RoverInterface.cpp, src/drivers/rover_interface/RoverInterface.hpp, src/drivers/rover_interface/rover_interface_params.c
- kill switch sub directly to action request topic, reducing delay from 500ms to ~200ms
- increase actuator control sub interval to 50ms (now matching fognav setpoint pub rate); this helps with the can connection drop issue due to low iob. Tested with UGV in UAE outdoor which lasted around 1.5hr back to back missions.
- enable bunker airframe 50006 in rc.rover_apps
=> Ugv support upgrade

platforms/common/uORB/uORBDeviceNode.cpp
In SITL case the _POSIX_NAME_MAX is only 14, so it fails for every topic. Use NAME_MAX instead to get correct maximum filename value for both posix and nuttx cases.
log snippet from sitl-test run:
```
[   3.129|px4       ] ERROR [uORB] Device node name too long! 'sensor_baro'
[   3.137|px4       ] ERROR [uORB] Device node name too long! 'tune_control'
[   3.143|px4       ] ERROR [uORB] Device node name too long! 'manual_control_setpoint'
[   3.147|px4       ] ERROR [uORB] Device node name too long! 'sensors_status_mag'
[   3.147|px4       ] ERROR [uORB] Device node name too long! 'sensors_status_baro'
[   3.148|px4       ] ERROR [uORB] Device node name too long! 'sensor_selection'
[   3.148|px4       ] ERROR [uORB] Device node name too long! 'sensors_status_imu'
[   3.148|px4       ] …
```
=> uorb: _POSIX_NAME_MAX -> NAME_MAX

platforms/nuttx/src/bootloader/microchip/mpfs/main.c, src/include/image_toc.h
This adds an ARB counter define for ssrc targets. This counter filed in the TOC is used by the new bootloader (saluki_bootloader_v2).
It also updates the TOC field name reserved -> flags2 in the old bootloader code to keep the old bootloader compilable. That change has no effect on ARB functionality
=> Add arb support

src/systemcmds/netconfig/CMakeLists.txt, src/systemcmds/system_time/CMakeLists.txt, src/systemcmds/topic_listener/CMakeLists.txt, src/systemcmds/tune_control/CMakeLists.txt, src/systemcmds/uorb/CMakeLists.txt, src/systemcmds/work_queue/CMakeLists.txt
These are simple and stateless applications -> NO_DAEMON saves 1 process and socket from being created for nothing.
=> systemcmds/xx: Turn some systemcmds into a non-daemon task

platforms/common/uORB/uORBDeviceNode.hpp
In kernel mode there might be quite a lot of waiters, so increase the callback list size substantially. Leave the other modes unaffected.
=> uORB/callbacks: Increase amount of callbacks to 32 in kernel mode

platforms/common/include/px4_platform_common/sem.h
This is a (temporary) regression mitigation after NuttX 12.0 release, where priority inheritance (pi) was disabled by default. This changes the default behavior, as previously pi was enabled by default.
Patch it by enabling it within the px4_sem_init() call.
=> px4_platform_common/sem.h: Enable SEM_PRIO_INHERIT by default

platforms/common/uORB/uORBDeviceNode.cpp, platforms/common/uORB/uORBManager.cpp, platforms/common/uORB/uORBManager.hpp
There is one semaphore lock per thread already, this same mechanism can be used to pass the callbacks too.
=> uorb: Move global _callback_ptr to per thread callback pointer

platforms/common/uORB/SubscriptionBlocking.hpp, platforms/common/uORB/uORBDeviceNode.cpp, platforms/common/uORB/uORBManager.cpp
There was some weirdness in uORBDeviceNode::copy; the queue indicies are not managed properly at least in wrap-around case
=> Fix uorb queue wraparound

platforms/nuttx/src/bootloader/microchip/mpfs/main.c, platforms/nuttx/src/px4/microchip/microchip_common/include/px4_arch/device_info.h, platforms/nuttx/src/px4/microchip/mpfs/include/px4_arch/device_info.h, platforms/nuttx/src/px4/microchip/mpfs/version/board_mcu_version.c, src/systemcmds/ver/ver.cpp
This adds the bootloader and FPGA version numbers to PX4 "ver" command. Cherry-picked from fc-only branch
=> Add version numberings to ver

src/drivers/rover_interface/RoverInterface.cpp, src/drivers/rover_interface/RoverInterface.hpp
- use vehicle thrust and torque setpoint instead of actuator controls
Tested in gz sim
=> rover interface: update

src/modules/simulation/gz_bridge/GZBridge.cpp
Increased limit value to avoid timeout while waiting for simulation clock in locally started simulation (make px4_sitl gz_x500)
=> gz_bridge: Increase sleep_count_limit to avoid timeout in local gz env

platforms/common/uORB/uORBDeviceNode.hpp, platforms/common/uORB/uORBManager.cpp, platforms/common/uORB/uORBManager.hpp
=> uORBManager: Cleanup for callbacks, semaphores etc

msg/CMakeLists.txt, msg/UlogStreamAck.msg, msg/UlogStreamAcked.msg, src/modules/logger/CMakeLists.txt, src/modules/logger/Kconfig, src/modules/logger/log_writer.cpp, src/modules/logger/log_writer.h, src/modules/logger/log_writer_mavlink.cpp, src/modules/logger/log_writer_mavlink.h, src/modules/logger/logger.cpp, src/modules/logger/logger.h, src/modules/logger/parallel_mavlink_logging.md, src/modules/mavlink/CMakeLists.txt, src/modules/mavlink/Kconfig, src/modules/mavlink/mavlink_ulog.cpp, src/modules/mavlink/mavlink_ulog.h
Flight logging over Mavlink is improved with parallel logging feature.
more info in src/modules/logger/parallel_mavlink_logging.md file
Parallel logging is enabled by adding following defines:
CONFIG_MAVLINK_PARALLEL_LOGGING
CONFIG_LOGGER_PARALLEL_LOGGING
=> Mavlink logger speedup config

platforms/common/uORB/uORBManager.cpp, platforms/nuttx/src/px4/common/px4_kmmap.c
Utilize the kmm_map interface to do px4_kmmap (for uORB mainly). This removes the 1 page restriction for kernel side mappings.
=> px4_kmmap.c: Implement px4_kmmap "properly"

platforms/common/include/px4_platform_common/sem.h
Temporary change, remove when semaphores work properly in kernel mode
=> [REVERTME] Disable semaphore PI for CONFIG_BUILD_KERNEL

platforms/common/uORB/SubscriptionCallback.hpp, platforms/common/uORB/uORBManager.cpp, platforms/common/uORB/uORBManager.hpp
Just some sanity checks added.
The uORB crash is "fixed" by the !sub->registered() check. Root cause for problem unknown.
=> uORB: Add some trivial sanity checks / fix possible race conditions

src/modules/logger/logger.cpp
Due to the current structure, if there is reliable transfer done in dynamic data stream while the static data transfer is still ongoing, the acked data stream gets corrupted (two consecutive data transfer).
Until the logger implementation is restructured to have dedicated fifo for reliable transfer data, we need to disable reliable transfers from dynamic data stream in parallel logging case.
=> Parallel_logging: Disable reliable_transfer for dynamic ADD_LOGGED_MSG

.github/workflows/tiiuae-coverity-scan.yaml, packaging/Dockerfile.coverity, packaging/coverity.yaml, packaging/entrypoint_coverity.sh
- update coverity 2023.06
- include list of scan findings in the action summary
- include full coverity report as zipped artifact on action
an example: https://github.com/tiiuae/px4-firmware/actions/runs/6635891574
=> DP-6244 enable coverity

.github/workflows/tiiuae-pixhawk-and-saluki.yaml, .github/workflows/tiiuae-pixhawk-artifact-publish.yaml, build.sh
The "px4 bootloader" is no longer supported for these
Target to be removed later in submodules
=> Remove building ssrc target bootloaders in CI

ROMFS/px4fmu_common/init.d-posix/airframes/4003_gz_rc_cessna, ROMFS/px4fmu_common/init.d-posix/airframes/4004_gz_standard_vtol, ROMFS/px4fmu_common/init.d-posix/airframes/4401_gz_ssrc_fog_x, ROMFS/px4fmu_common/init.d-posix/airframes/4440_gz_ssrc_skywalker_x8, ROMFS/px4fmu_common/init.d-posix/airframes/50005_gz_ssrc_scout_mini_rover, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt, ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator, ROMFS/px4fmu_common/init.d/airframes/50005_ssrc_scout_mini_rover, ROMFS/px4fmu_common/init.d/airframes/50007_ssrc_bunker_mini_rover, ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt, packaging/Dockerfile.sitl_gzsim, packaging/build_px4_sitl_gzsim.sh, packaging/entrypoint_sitl_gzsim.sh, src/drivers/rover_interface/RoverInterface.cpp, src/drivers/rover_interface/RoverInterface.hpp, src/drivers/rover_interface/rover_interface_params.c, src/modules/rover_pos_control/RoverPositionControl.cpp, src/modules/rover_pos_control/RoverPositionControl.hpp, src/modules/rover_pos_control/rover_pos_control_params.c, src/modules/simulation/gz_bridge/GZBridge.cpp, src/modules/simulation/gz_bridge/GZBridge.hpp, src/modules/simulation/gz_bridge/parameters.c, src/modules/simulation/sensor_gps_sim/SensorGpsSim.cpp
- rover pos control: fix ugv stuttering issue, enable stationary rotation and smooth path following
- Add new px4 sitl build files for building px4 sitl container that's compatible with cloud simulation (dronsole) and gz sim
- Add new and modify some gz sim airframes and normal airframes
- rover interface: support in flight manual speed scaling and mission max speed scaling
The rover pos control fixes were tested with previous main on UGV2 and again in gz sim with the new rebase main (to verify the actuator control msg change to vehicle torque and thrust setpoint msg)
All other changes were tested in gz sim
=> New GZ SIM compatible SITL build and rover fixes

src/modules/uxrce_dds_client/dds_topics.yaml
There is no one using the position_setpoint_triplet messages in MC side currently and because no users there, it causes SROS ACL errors about uxrce-agent has no permissions to write to topic.
=> uxrce_client: Do not send PositionSetpointTriplet

.gitmodules
So we can cherry-pick changes for nuttx-apps. This change maybe worth reverting at some point (make nuttx-apps point to some release again).
=> gitmodules: Set nuttx-apps remote to tiiuae/nuttx-apps/master

platforms/nuttx/src/px4/microchip/mpfs/version/board_mcu_version.c
This allows using R&D certificate for UART enabling
=> Disable uart

packaging/Dockerfile.build_env
When building under OSX the typical user group (staff) has a GID of 20 conflicting with some Ubuntu system group of the container. Additionally if the git users between the host and container don't match (repo cloned on host, used in container), git aborts with a fatal error. 
- Add '-o' option to groupadd to allow for multiple group names pointing to the same GID
- Mark the sources directory as a 'safe.directory' for git inside the container
- '-o' option: perhaps we could use the existing group name but I suppose that would add too much bloat in the dockerfile
- git safe dir: perhaps we could COPY the host's user git config over to the container though I'm not sure of how portable that can be.
- Tested only under OSX.
=> Fix osx build and git user conflict

.github/dependabot.yml, .github/workflows/tiiuae-pixhawk-and-saluki.yaml, Tools/px_uploader.Dockerfile
These files are packaged together to enable fpga, bootloader_v2 and pixhawk binaries all from one container
=> DP-7313 add fpga and bootloader-v2 binaries to px4 container

platforms/common/include/px4_platform_common/shutdown.h, platforms/common/shutdown.cpp, platforms/nuttx/src/px4/microchip/mpfs/board_reset/board_reset.cpp, src/systemcmds/reboot/reboot.cpp
Support for calling reboot with "continue boot" flag to let bootloader to start PX4 instead of keep looping and waiting for reflashing. This feature makes possible in LMC case to update PX4 firmware into mounted root partition and call "reboot-and-continue-boot" to take the new PX4 image into use.
Reset in "continue boot" case is performed by watchdog reset, so bootloader does not stay looping for reflash.
The reboot systemcmd also updated to have "-c" flag in addition to "-b" to reboot to bootloader and continue boot back to PX4.
=> Reset continue boot option

.gitmodules, clone_public.sh, packaging/build_px4fw.sh
This is a cherry-pick from 1.13.3 branch to 1.14
====================
If SIGNING_ARGS environment variable is defined, build script uses its value as a signing key location.
Also a new submodule saluki-sec-scripts is added. If SIGNING_ARGS is not defined test keys are used under Tools/saluki-sec-scripts/test_keys/
saluki-sec-scripts contains also signing tools and second set of keys (custom_keys), which are used in FPGA secure boot builds.
=> Add support to define PX4 signing key via env. variable

msg/CMakeLists.txt, msg/SystemVersion.msg, msg/SystemVersionString.msg, platforms/nuttx/src/px4/microchip/microchip_common/include/px4_arch/device_info.h, platforms/nuttx/src/px4/microchip/mpfs/version/board_mcu_version.c
This adds version information into uORB topics, allowing easy version information pulishing to ROS (uXRCE) and access from applications in memory protected build modes of PX4
=> Add version messages

platforms/common/uORB/uORBManager.hpp
This fixes the uORB signaling semaphores, they should not use priority inheritance
#if __PX4_NUTTX does nothing, change it to #if defined()
=> uORB/uORBManager.hpp: Fix pre-processor condition

platforms/common/include/px4_platform_common/crypto.h, platforms/common/include/px4_platform_common/crypto_backend.h, platforms/nuttx/src/px4/common/px4_crypto.cpp, platforms/nuttx/src/px4/common/px4_usr_crypto.cpp, src/drivers/sw_crypto/crypto.c, src/modules/logger/log_writer_file.cpp, src/modules/logger/log_writer_file.h, src/systemcmds/tests/CMakeLists.txt, src/systemcmds/tests/test_crypto.cpp, src/systemcmds/tests/tests_main.c, src/systemcmds/tests/tests_main.h
This is the first PR for enabling more crypto interfaces.
Next steps are to enable aes256 and write implementation for decrypting for xchacha and aes (for pfsoc crypto only)
=> Add more crypto interfaces

.github/workflows/checks.yml, .github/workflows/compile_linux.yml, .github/workflows/compile_linux_arm64.yml, .github/workflows/compile_macos.yml, .github/workflows/compile_nuttx.yml, .github/workflows/ekf_update_change_indicator.yml, .github/workflows/mavros_mission_tests.yml, .github/workflows/mavros_offboard_tests.yml, .github/workflows/sitl_tests.yml, .github/workflows/tiiuae-coverity-scan.yaml, .github/workflows/tiiuae-pixhawk-and-saluki-builder.yaml, .github/workflows/tiiuae-pixhawk-and-saluki.yaml, .github/workflows/tiiuae-sitl.yaml, src/modules/ekf2/EKF/python/tuning_tools/baro_static_pressure_compensation/requirements.txt, src/modules/ekf2/EKF/python/tuning_tools/mc_wind_estimator/requirements.txt
Combination of multiple dependabot updates:
build(deps): bump scipy
Bumps [scipy](https://github.com/scipy/scipy) from 1.8.0 to 1.10.0.
- [Release notes](https://github.com/scipy/scipy/releases)
build(deps): bump actions/upload-artifact from 2.pre.preview to 3.1.3 Bumps [actions/upload-artifact](https://github.com/actions/upload-artifact) from 2.pre.preview to 3.1.3.
- [Release notes](https://github.com/actions/upload-artifact/releases)
build(deps): bump docker/setup-buildx-action from 2 to 3 Bumps [docker/setup-buildx-action](https://github.com/docker/setup-buildx-action) from 2 to 3.
- [Release notes](https://github.com/docker/setup-buildx-action/releases)
build(deps): bump stefanzweifel/git-auto-commit-action from 4 to 5 Bumps …
=> Dependabot updates

.github/workflows/tiiuae-blackduck-scan.yaml
Run blackduck scan always when a tag v1.14.0-* is pushed
=> run blackduck scan on pushed tags

platforms/common/uORB/uORBDeviceNode.cpp, platforms/common/uORB/uORBDeviceNode.hpp
Just changing things that looked odd to me.
ATOMIC_ENTER / ATOMIC_LEAVE should probably be used consistently; In flat build use the critical_section in all places, just like in protected builds it uses the semaphore.
=> platforms/common/uORB/uORBDeviceNode: Make consistent use of ATOMIC_ENTER 

.github/workflows/tiiuae-pixhawk-and-saluki-builder.yaml, .github/workflows/tiiuae-pixhawk-and-saluki.yaml, Tools/px_uploader.Dockerfile, build.sh
- add saluki v2, v3 and pi with custom keys
- don't add bootloader to px4 container
- add signing args
=> build px4 custom signed binaries

platforms/common/uORB/IndexedStack.hpp, platforms/common/uORB/SubscriptionCallback.hpp, platforms/common/uORB/uORBDeviceNode.cpp, platforms/common/uORB/uORBDeviceNode.hpp, platforms/common/uORB/uORBManager.cpp, platforms/common/uORB/uORBManager.hpp
This changes the way how uORB callbacks are executed;
- The callback subscriptions are collected in a list withing each process
- The priority of the processes' callback thread is set to the maximum thread priority within the process
- All the triggred callbacks are executed in a loop when the callback thread gets to run
Signalling the callback
- The publisher marks the callback as "triggered" and signals the callback thread. There is no synchronization back from the callback thread potentially allowing the publisher to fire all the registered callbacks/polls at once withouth scheduling away at each signalling semaphore post.
=> Uorb optimization3

ROMFS/px4fmu_common/init.d-posix/CMakeLists.txt, ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator, ROMFS/px4fmu_common/init.d-posix/rcS.sim_tcp_server, ROMFS/px4fmu_common/init.d-posix/rcS.sim_udp, packaging/entrypoint.sh
Fix SITL gazebo connection type selection
In docker run command use --env to select connection type:
- `--env=PX4_SIM_USE_TCP_SERVER=1`     => PX4-sitl acts as TCP server 
- `--env=PX4_SIM_USE_UDP=1`     => PX4-sitl uses UDP
- default => PX4-sitl acts as TCP client (this is how upstream IRIS model works)
=> SITL: select UDP/TCP-server/TCP-client according to ENV variables

ROMFS/px4fmu_common/init.d-posix/airframes/4400_ssrc_fog_x, ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator, ROMFS/px4fmu_common/init.d-posix/rcS
- Upstream commit to fix parse error on start with gazebo simulation.
-  Fixes `etc/init.d-posix/rcS: 39: [: Illegal number:`
- Add `set SDCARD_AVAILABLE no` to prevent parse error.
- Fixes `/px4_sitl_etc/init.d-posix/rcS.sim_udp: 26: [: =: unexpected operator`
- Fix ssrc_fog_x airframe for gazebo classic simulation. Original commit before rebase: https://github.com/tiiuae/px4-firmware/commit/fe293c4fcfb53cb40bed926d1b8e8fb2d64f8811
Not sure if this breaks anything with the gz-sim simulations. Needs to be verified.
=> Fix gazebo classic simulation

src/modules/mavlink/mavlink_ulog.cpp
ulog_stream_acked uorb shall be synced with update() call even check_for_updates not set.
If update not called, it may lead to infinite loop in case check_for_updates not set and there are new messages in ulog_stream_acked uorb.
=> mavlink_ulog: always update ulog_stream_acked uorb 

platforms/nuttx/src/px4/common/px4_init.cpp
Like __dso_handle, this symbol must NOT be pulled from the user libc. The __cxa_atexitatexit() functions in kernel are no-ops as we don't support shared library destructors.
This fixes uavcan for kernel mode
=> px4_init.cpp: Define __cxa_atexit() here

ROMFS/px4fmu_common/init.d/airframes/4401_ssrc_fog_x_tmotor
Previous tune change did not behave well on other units of the M690B frame. This tune has been flown in Finland and UAE on 2 separate frames and is more stable than the old preset.
=> Updated 4401 (M690B) tuning parameters for more stable flight

platforms/common/uORB/uORBDeviceNode.cpp
In case the callback has bee posted by DeviceNode::Write, but not yet handled by the callback thread, we must cancel the posts after removing the cb from the list of callbacks.
=> uORBDeviceNode: Fix race with _unregister_callback

.github/workflows/tiiuae-pixhawk-and-saluki.yaml
This is because our uae upload token has expired and it causes CI builds to get failed status
=> disable uae artifactory uploads temporarily

platforms/common/uORB/uORBDeviceNode.cpp, platforms/common/uORB/uORBDeviceNode.hpp, platforms/common/uORB/uORBManager.cpp
Try to fix the original problem in a preper way;
Only take the synhcronizing semaphore in the callback thread; just take into account how many times the callback has been triggered but not handled.
This seems to work correctly in SITL: not tested on the hw so far
The original fix had a huge regression; the publisher thread was getting blocked by the semaphore. Now try the fix the same issue in the way that only place where the snchronizing semaphore is taken is actually the callback thread
=> Fix uorb again

src/modules/mavlink/mavlink_ulog.cpp
In while loop condition, check pending acked uorb messages only in case we are not waiting for ack for the previous acked mavlink message.
=> mavlink_ulog deadlock fix

Tools/px_uploader.Dockerfile
The script is copied from
https://github.com/tiiuae/saluki_bootloader_v2/blob/master/tools/px_uploader.py
This is a short term fix. In the long we better have one script in one place
=> DP-8235 bootloader_v2 compatible px_uploader.sh to px4 image container

platforms/common/uORB/uORBDeviceNode.cpp, platforms/common/uORB/uORBDeviceNode.hpp, platforms/common/uORB/uORBManager.cpp, platforms/common/uORB/uORBManager.hpp
This is another fix for the previous issue. It tries to remove the remaining race conditions from the callback counter handling.
A simpler fix obviously would be to remove the whole counter, but that would cause the callback loop spinning a lot more, and taking the mutexes inside are rather heavy. I measured this to eat ~2pp of CPU on a "standard configuration", so trying to keep the counter in.
=> uORB: Fix the remaining race conditions from callback unregistration

platforms/nuttx/src/px4/common/console_buffer.cpp, platforms/nuttx/src/px4/common/console_buffer_usr.cpp, platforms/nuttx/src/px4/common/px4_userspace_init.cpp
Implements user space version of buffered console. Uses the /dev/console device.
This fixes SD card flight logs in kernel mode.
=> console_buffer: Implement console_buffer_usr

src/modules/logger/log_writer.cpp, src/modules/logger/log_writer.h, src/modules/logger/log_writer_mavlink.cpp, src/modules/logger/log_writer_mavlink.h, src/modules/logger/logger.cpp, src/modules/logger/logger.h, src/modules/logger/messages.h, src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_ulog.cpp, src/modules/mavlink/mavlink_ulog.h
This contains the code from mavlink-logging-ack-timeout-increased branch. Commits are squashed and cherry-picked on top of latest main.
Functionality verified: https://ssrc.atlassian.net/wiki/spaces/DRON/pages/811761775/Indoor+Test+Memo#14.3.2024-Misc-Testing
=> Mavlink logging refactor

.github/workflows/tiiuae-pixhawk-and-saluki.yaml, build.sh
This fixes https://ssrc.atlassian.net/browse/DP-7919 , turns on CONFIG_BUILD_KERNEL for default and amp targets for saluki-v2, saluki-pi and saluki-v3
=> Enable kernel mode in ssrc targets

platforms/common/uORB/SubscriptionCallback.hpp, platforms/common/uORB/SubscriptionInterval.hpp, platforms/common/uORB/uORBManager.cpp
This fixes an issue found with "topic_listener <topic> -r 1" command;
The topic which is subscribed with a rate of 1 second is initially given twice, and after that every 1 second.
The time when the topic was last updated can't be initialized to 0. The best possible initial value is "now - interval", which gives the subscriber the first publish after subscription, and after that according to the interval.
=> Improve uorb subscription interval handling

src/modules/logger/logger.cpp
This is a cherry-pick from upstream px4, fixing https://ssrc.atlassian.net/browse/DP-8252
-----------------------
When the CPU load monitor is started while already running, then the idle thread last_times[0] is reset to the last 1 second, rather than since when the CPU load monitor was last started. The remaining threads are not impacted, since their last_times[i] is reset to zero here.
This results in the idle thread having a lower than real CPU load, with the remaining CPU time being wrongly attributed as scheduler load.
=> cpuload: Fix wrong idle thread load

platforms/nuttx/src/px4/microchip/mpfs/version/board_mcu_version.c
The data was not copied in the correct place inside the topic structure
=> Fix version topic publish

platforms/common/uORB/uORBDeviceNode.cpp, platforms/common/uORB/uORBManager.cpp
In memory protected modes there were the following issues:
1. It is wrong to self-unregister the callback in uORBDeviceNode. The device node can't assume that the callback thread is killed if the callbacks haven't been handled timely. It might also be temporarily blocked e.g. during boot. If the device node unregisters the callback and the callback thread gets executed later, the cb_handle would point to an item within the device node that is not any more in use.
2. While registering a callback, it has to be registered to both callback thread and the device node before letting callback thread handle them.
Fix these issues as follows:
1. Don't let the device node unregister the callback by itself
2. Keep the callback list locked for the full registration of the callback
In addition, make a …
=> uORB: Fix uORB callback register/unregister issues

.github/workflows/tiiuae-pixhawk-and-saluki.yaml, Tools/collect_json_files.py, Tools/compile_px4_build_info.py, Tools/fetch-fpga-files.sh, Tools/generate_basic_build_info.sh, Tools/px_uploader.Dockerfile, build.sh
Port from px4-firmware-fc-only:
saluki_file_info.json contains info about the build. It has links where did the build come from and what is the build content (filename, hw, bin type, etc). This is included in bootloader, fpga and px4 repos. Flashing tool will be updated to read this info.
This change will
- Use saluki_file_info.json file for donwloading correct fpga files and bootloader info
- Generate saluki_file_info.json to contain info about the build
- Use FPGA from saluki-fpga repo instead of saluki-pi/fpga
=> use saluki_file_info.json

.github/workflows/tiiuae-codeql.yaml
CodeQL needs to be ran on push to main. Otherwise the github status page stays out of sync
=> run codeql on push to main branch

src/modules/mavlink/mavlink_params.c, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h, src/modules/mavlink/streams/HIL_ACTUATOR_CONTROLS.hpp, src/modules/simulation/gz_bridge/GZBridge.cpp, src/modules/simulation/gz_bridge/GZBridge.hpp, src/modules/simulation/gz_bridge/parameters.c
- Add support for esc_status uorb msg in HITL mode. It will be needed for tests that requires failure injection
- Add support for receiving home GPS position and option to use it instead of default px4 home GPS coordinates
Tested in SITL and HITL
=> Gz sim simulation improvements

src/modules/sensors/CMakeLists.txt, src/modules/sensors/failure_detector_HITL/CMakeLists.txt, src/modules/sensors/failure_detector_HITL/failure_detector_HITL.cpp, src/modules/sensors/failure_detector_HITL/failure_detector_HITL.hpp, src/modules/sensors/sensors.cpp, src/modules/sensors/sensors.hpp, src/modules/sensors/vehicle_air_data/VehicleAirData.cpp, src/modules/sensors/vehicle_air_data/VehicleAirData.hpp, src/modules/sensors/vehicle_gps_position/VehicleGPSPosition.cpp, src/modules/sensors/vehicle_gps_position/VehicleGPSPosition.hpp, src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp, src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.hpp
Component: Introduced failure_detector_hitl module, integrating three classes for handling failure injection messages(FailureDetectorHITL),
simulating sensors that have ceased to update (FakeStuckSensor), and a component managing a collection of these simulated sensors (FakeSensors).
This module is a combination of three classes: FailureDetectorHITL for detecting failure injection messages, FakeStuckSensor for simulating sensors whose readings have become stuck, and FakeSensors, a component that aggregates a collection of such simulated sensors.
Additionally, the handling of the sensors module has been extended to support disabling sensors during flight.
Designed exclusively for operation in HITL (Hardware-In-The-Loop) mode, this module does not interfere with normal operational mode. …
=> Feature: failure detector hitl

platforms/common/uORB/uORBManager.cpp
A curly brace was misplaced, calls to unlock_cb_list() etc belong within the statement
if (cb_lock >= 0) {
}
=> uORBManager.cpp: Fix issue with registerCallback

src/drivers/barometer/bmp388/bmp388.cpp, src/drivers/barometer/bmp388/bmp388.h, src/drivers/barometer/bmp388/bmp388_i2c.cpp, src/drivers/barometer/bmp388/bmp388_spi.cpp
cherry-picked fix from upstream: https://github.com/PX4/PX4-Autopilot/commit/e202e719b04962bb7cf87aa62f1892c580cf7055
```
bmp388: check bus return code after register read
Check I2C/SPI bus transfer function return code after register read operation.
```
=> [mavlink 200Hz 1/2] bmp388 sensor fix from upstream

platforms/common/uORB/uORBManager.cpp, platforms/common/uORB/uORBManager.hpp
This optimizes one loop when reserving new signaling semaphore.
=> uORBManager.cpp: Use InxedexStack for global semaphore list

platforms/common/include/px4_platform_common/crypto.h, platforms/common/include/px4_platform_common/crypto_backend.h, platforms/nuttx/src/px4/common/px4_crypto.cpp, platforms/nuttx/src/px4/common/px4_usr_crypto.cpp, src/drivers/sw_crypto/crypto.c, src/systemcmds/tests/test_crypto.cpp
Added implementation for PX4Crypto::sign() and PX4Crypto::generate_keypair()
Added key_type (PRIVATE/PUBLIC) into key_cache and modified der_parse function list to support parser for both.
tests/test_crypto: Implemented ed25519 key generate and signing/signatyre_verification tests
=> Ed25519 sign support

src/systemcmds/tests/CMakeLists.txt, src/systemcmds/tests/tests_main.c
Remove bson test from kernel-mode build.
Tinybson lib is located in kernel space and can't be accessed from user side tests app
Removal can be selected with config flag CONFIG_TESTS_KERNEL_MODE_COMPATIBLE 
to separate it out from kernel-mode builds only
=> Remove bson test for kernel-mode build

src/drivers/uavcan/actuators/esc.cpp
- Since the Myxa ESC current report is not correct, esc current should be set to 0 to disable the current probe in failure detector to avoid wrongly trigger of `Preflight Fail: Motor failure detected`
=> uavcan: disable esc current report

msg/CMakeLists.txt, msg/SensorTvs.msg, platforms/nuttx/src/px4/microchip/mpfs/include/px4_arch/tvs.h, platforms/nuttx/src/px4/microchip/mpfs/tvs/CMakeLists.txt, platforms/nuttx/src/px4/microchip/mpfs/tvs/mpfs_tvs.c, src/drivers/tvs/CMakeLists.txt, src/drivers/tvs/Kconfig, src/drivers/tvs/tvs.cpp, src/drivers/tvs/tvs.hpp
Added driver for MPFS TVS (temperature and voltage sensor) FPGA block and a new uORB topic (sensor_tvs). The driver is cherry-picked from 1.13_fc_only.
Reporting period is 500ms
```
TOPIC: sensor_tvs
sensor_tvs
timestamp: 276847808 (0.438826 seconds ago)
device_id: 16711936 (Type: 0xFF, UNKNOWN:0 (0x01))
temperature: 46.22501
voltage: [987.87500, 1790.12500, 2499.87500]
saluki> 
saluki> tvs status
INFO  [tvs] TVS voltage 1.0 V: 987.875 mV
INFO  [tvs] TVS voltage 1.8 V: 1786.250 mV
INFO  [tvs] TVS voltage 2.5 V: 2499.875 mV
INFO  [tvs] TVS temperature:   47.663 Celcius
saluki> 
```
=> MPFS TVS: driver and new uORB topic [1/4]

.github/workflows/tiiuae-pixhawk-and-saluki.yaml
Doesn't really change anything on px4 side, just adds fmu2 files to output container
=> package FMU2 FPGA files to output container

.github/workflows/tiiuae-pixhawk-and-saluki.yaml, Tools/px_uploader.Dockerfile, Tools/px_uploader.entrypoint
Extract px4 files in px4 container's entrypoint
Removed old shell commands which were for the update with old bootloader and didn't work anymore.
Generate metadata needed for saluki sw update
- validation file with px4 build timestamp
- updated json file for extracted binaries
=> PX4 update: export px4 binaries to temp dir

ROMFS/px4fmu_common/init.d/airframes/4420_ssrc_arwing, ROMFS/px4fmu_common/init.d/airframes/4421_ssrc_skywalker, ROMFS/px4fmu_common/init.d/airframes/4430_ssrc_strivermini, src/drivers/differential_pressure/ms4525do/MS4525DO.hpp, src/drivers/differential_pressure/sdp3x/SDP3X.hpp, src/systemcmds/telem_test/CMakeLists.txt, src/systemcmds/telem_test/Kconfig, src/systemcmds/telem_test/telem_test.cpp
Telem_test application and airspeed sensor fixes ported from 1.13_fc_only:
-telem_test application runs simple write/read loopback test between 2 telemetry uart ports (HW test)
-MS4525DO and SDP3X sensor I2C default speed set to 400 kHz and related sensor start workarounds removed
=> Port from 1.13_fc_only to main [1/4]

platforms/nuttx/NuttX/CMakeLists.txt
Assembly files are now handled correctly as dependencies (for e.g. libarch)
=> NuttX libraries: Add Assembly sources to dependency list

Tools/px_uploader.Dockerfile, Tools/px_uploader.entrypoint, build.sh, src/lib/version/px_update_git_header.py, src/lib/version/version.c, src/lib/version/version.h, src/systemcmds/ver/ver.cpp
- include build time to generated build_git_version.h. This is done to get the build timestamp to docker container saluki_file_info.json file and it will match to px4 version library. It can then be used to ota update to know if the image is newer or older. 
- Also to reduce container size changed the px4 container so it doesn't have python anymore as it is not needed.
- build.sh had 14 almost equal switch cases so that is now redone to be more generic
=> Build epoch time

platforms/nuttx/src/px4/microchip/mpfs/version/board_mcu_version.c
FPGA DIE type and speed grade information is available in fgpa version register area:
https://github.com/tiiuae/saluki-fpga/tree/main/ssrc_saluki-pi#fpga-version-info-register
This information is appended to FPGA version string. E.g. `FPGA: 2.65535 (0xffff0243), MPFS250 (SG 1)`
Also `component_version1`-field size increased to match `static char fpga_info[64]` in `platforms/nuttx/src/px4/microchip/mpfs/version/board_mcu_version.c`
```
saluki> ver all
HW arch: SSRC_SALUKI_PI
HW type: Saluki003000
HW version: 0x003
HW revision: 0x000
PX4 git-hash: df811b9bd62aac1eba34f9b3d2c643529724bc79
PX4 version: 1.14.0 0 (17694720)
PX4 git-branch: mpfs_die_type
Bootloader version: 1.4.0
Accelerator version: FPGA: 2.65535 (0xffff0243), MPFS250 (SG 1)
Vendor version: 12.0.1 0 (201326848)
OS: NuttX
OS …
```
=> FPGA version: DIE type and speed grade

ROMFS/px4fmu_common/init.d-posix/airframes/4401_gz_ssrc_fog_x, ROMFS/px4fmu_common/init.d-posix/airframes/4440_gz_ssrc_skywalker_x8, ROMFS/px4fmu_common/init.d-posix/airframes/50005_gz_ssrc_scout_mini_rover, src/modules/mavlink/mavlink_params.c, src/modules/mavlink/mavlink_receiver.cpp, src/modules/simulation/gz_bridge/parameters.c, ssrc_config/config_hitl_eth_gzsim.txt
This patch re-enable the publishing of `sensor_gps` received from mavlink msg `HIL_GPS` in case of non-HITL when then `MAV_USEHILGPS` param is enabled. Although there is no use of `MAV_USEHILGPS` in our system, this is a house keeping patch to fix the backward incompatibility the commit https://github.com/tiiuae/px4-firmware/commit/053f9250e9ad3598d99e5bff786f4709fa624093 previously introduced
Also, it makes the use of GPS home position from gzsim disabled by default. This feature should only be enabled for SITL and HITL use with gz-sim-server container (gazebo garden)
Tested with `make px4_sitl_default gz_x500`
=> mavlink: re-enable sensor_gps pub for SITL from HIL_GPS mavlink msg

.gitmodules, Tools/simulation/gz/hitl_run.sh, Tools/simulation/gz/models/ssrc_holybro_x500/model_hitl.sdf, Tools/simulation/gz/models/x500/model_hitl.sdf, src/modules/simulation/gz_bridge/gz_env.sh.in, src/modules/simulation/simulator_mavlink/CMakeLists.txt, src/modules/simulation/simulator_mavlink/sitl_targets_gz-sim.cmake
Support for using gz sim in hitl mode includes:
- using this mavlink plugin for connection with a device https://github.com/tiiuae/px4-gzsim-plugins
- adding new sdf models
- adding new target for build (`make px4_sitl gz-sim`)
- a script for easy simulation execution (`./Tools/simulation/gz/hitl_run.sh x500/model_hitl.sdf`)
On branch feature_gzsim_support
Changes to be committed:
modified:   .gitmodules
new file:   Tools/simulation/gz/hitl_run.sh
new file:   Tools/simulation/gz/models/ssrc_holybro_x500/model_hitl.sdf
new file:   Tools/simulation/gz/models/x500/model_hitl.sdf
new file:   Tools/simulation/gz/plugins/px4-gzsim-plugins
modified:   src/modules/simulation/gz_bridge/gz_env.sh.in
modified:   src/modules/simulation/simulator_mavlink/CMakeLists.txt
new file: …
=> Support for running simulation with gz sim in hitl mode

src/systemcmds/ver/ver.cpp
Testing reported there is an extra line feed in ver all command:
```
OS version: Release 12.2.1 (201458175)
OS git-hash: d493bcdf064c25b0d145a5bd88f3a2af4cd8dd9f
Build date: Tue Jun  4 04:54:59 2024
Build uri: localhost
Build variant: default
```
appeared when timestamp was changed for ota update
=> remove extra line feed in ver all

platforms/nuttx/CMakeLists.txt
nsh is the init process, which resides in sbin/init. The user should not have rights to execute nsh.
=> build/bin: Remove nsh from the final ROMFS

src/drivers/imu/invensense/icm40609d/ICM40609D.cpp, src/drivers/imu/invensense/icm40609d/ICM40609D.hpp, src/drivers/imu/invensense/icm40609d/InvenSense_ICM40609D_registers.hpp
Enable the new sensor board for Saluki-FMU2
=> Enable the new sensor board for Saluki-FMU2

ROMFS/px4fmu_common/init.d-posix/airframes/4430_gz_ssrc_strivermini, ROMFS/px4fmu_common/init.d-posix/airframes/CMakeLists.txt, packaging/entrypoint_sitl_gzsim.sh
Add a gz model of the Striver Mini VTOL using realistic params
=> [DO NOT MERGE YET] Add a Striver Mini VTOL for Gazebo

Tools/msg/templates/uorb/msg.cpp.em, Tools/msg/templates/uorb/uORBTopics.cpp.em, Tools/msg/templates/uorb/uORBTopics.hpp.em, platforms/common/uORB/uORB.h, platforms/common/uORB/uORBDeviceNode.cpp, platforms/common/uORB/uORBManager.hpp, src/modules/logger/logged_topics.h, src/modules/logger/logger.h, src/modules/uxrce_dds_client/dds_topics.h.em, src/modules/uxrce_dds_client/utilities.hpp
These are cherry-picks from PX4 mainline, with some modifications to uORB (as we have an own version of that library).
The change is needed in order to support more than 255 uORB ID:s. We are very close to the limit, and currently it is not possbile to add new ones - which is needed by our own development (e.g. redundancy topics) and most likely by the customer as well.
=> Increase max uorbs

src/modules/uxrce_dds_client/dds_topics.yaml
Add following topics to microxrce publishers. Both topics are low frequency, shouldn't add much load. If the usage gets problematic, we can drop `EstimatorGpsStatus` as it is only used for the diagnostic view.
- ActuatorArmed -> used for determining the kill switch status from `manual_lockdown` flag
- EstimatorGpsStatus -> used for gps diagnostics. Using `checks_passed` and `check_fail_gps_fix`.
=> uxrce: add actuator_armed and estimator_gps_status topic publishers

platforms/nuttx/src/px4/common/usr_mcu_version.cpp
Matching change exists already on mpfs, this was probably accidentally not updated
=> fix device serial number reading on user side

platforms/nuttx/CMakeLists.txt
Only run the rule once i.e. if boot/init does not exist
=> nuttx/CMakeLists: Fix rule for renaming nsh -> init

src/drivers/pwm_esc/pwm_esc.cpp
This fixes "pwm_esc status" command ( https://ssrc.atlassian.net/browse/DP-9563 )and prepares for future HITL and redundancy work
=> Pwm esc improvements

src/lib/perf/perf_counter.cpp
Adding multiple instance support for performance counters.
Instance number is added to shared memory filename
```
saluki> ls /var/shm
...
_perf_bmp388: comms errors_0
_perf_bmp388: comms errors_1
_perf_bmp388: measure_0
_perf_bmp388: measure_1
_perf_bmp388: read_0
_perf_bmp388: read_1
```
Driver status output
```
saluki> bmp388 status
INFO  [SPI_I2C] Running on I2C Bus 1, Address 0x77
chip id:  0x60 rev id:  0x01
0: bmp388: read: 1965 events, 553165us elapsed, 281.51us avg, min 263us max 417us 17.823us rms
0: bmp388: measure: 1967 events, 674518us elapsed, 342.92us avg, min 308us max 12234us 269.558us rms
0: bmp388: comms errors: 1 events
measurement interval:  43300 us 
INFO  [SPI_I2C] Running on I2C Bus 2, Address 0x76
chip id:  0x60 rev id:  0x01
1: bmp388: read: 1963 events, 557289us …
```
=> perf counter: add support for multi-instance counters

platforms/nuttx/src/px4/nxp/imx9/version/board_mcu_version.c
This was one of the reason for sequential crashes in "flat" builds. Logger calls the version library with null errata pointer when logging in started. This may happen also during the boot depending on the parameters.
=> Fix logger crash

platforms/nuttx/src/px4/common/board_ioctl.c, platforms/nuttx/src/px4/common/hrt_ioctl.c, src/drivers/pwm_esc/pwm_esc.cpp
=> arm64 fixes

platforms/nuttx/src/px4/nxp/imx9/include/px4_arch/micro_hal.h, platforms/nuttx/src/px4/nxp/imx9/include/px4_arch/px4io_serial.h, platforms/nuttx/src/px4/nxp/imx9/px4io_serial/CMakeLists.txt, platforms/nuttx/src/px4/nxp/imx9/px4io_serial/px4io_serial.cpp, platforms/nuttx/src/px4/nxp/imx9/version/board_mcu_version.c
This enables PX4IO on our saluki-nxp93 HW
=> Enable px4io

ROMFS/px4fmu_common/init.d-posix/airframes/4404_gz_ssrc_standard_vtol, ROMFS/px4fmu_common/init.d-posix/airframes/4430_gz_ssrc_strivermini, ROMFS/px4fmu_common/init.d/airframes/4400_ssrc_fog_x, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/mavlink_receiver.h, src/modules/mavlink/streams/HIL_ACTUATOR_CONTROLS.hpp, src/modules/simulation/pwm_out_sim/PWMSim.cpp, src/modules/simulation/pwm_out_sim/PWMSim.hpp, src/modules/simulation/pwm_out_sim/module_hil.yaml, src/modules/simulation/sensor_airspeed_sim/SensorAirspeedSim.cpp, src/modules/simulation/sensor_airspeed_sim/SensorAirspeedSim.hpp, ssrc_config/config_hitl_eth_gzsim.txt, ssrc_config/config_hitl_eth_gzsim_fw.txt, ssrc_config/config_hitl_eth_gzsim_mc.txt, ssrc_config/config_hitl_eth_gzsim_rover.txt, ssrc_config/config_hitl_eth_gzsim_vtol_sm.txt, ssrc_config/config_hitl_eth_gzsim_vtol_sv.txt
- Add HITL support for FW (tested with Skywalker_x8 model)
- Add HITL support for VTOL (tested with standard_vtol and striver_mini models)
- Add HITL support for Rover (tested with scout_mini model)
- Mavlink receiver: remove unused Airspeed data reception from Gz (use sensor_airspeed_sim instead)
Related PR https://github.com/tiiuae/px4-gzsim-plugins/pull/9, https://github.com/tiiuae/gz-models/pull/4
=> Add HITL support for fw, vtol and rover

src/modules/commander/failsafe/failsafe.cpp
This PR fetches the upstream changes introduced in this PR. ([#<span></span>23569](https://github.com/PX4/PX4-Autopilot/pull/23569))
In summary:
- When there is a failsafe condition such as RC loss with Land as failsafe action, the land operation is cleared once the RC signal is regained. This is not the same with the RTL, where it doesnt get cleared out. When the land failsafe action is cleared, it goes back to user intention nav state, which is not desirable.
- This PR prevent clearing the Land failsafe if the cause has been solved. Once it switches to Land failsafe, it will finalize that action unless mode changed manually or disarmed.
**_This change should be removed during the rebasing to a newer version of PX4-firmware._**
=> Commander: Failsafe: set clear condition for action Land like for RTL

platforms/nuttx/NuttX/Make.defs.in
The aarch64 compiler does not like some attributes used by NuttX, so suppress the warning.
The flag is used in upstream as well.
=> nuttx/Make.defs.in: Support for ARM64

src/modules/mavlink/mavlink_main.cpp
Enable **partner IP** to be printed in mavlink status output also other than POSIX (SITL) build
Example:
```
instance #1:
mavlink chan: #1
type:           GENERIC LINK OR RADIO
flow control: OFF
rates:
tx: 1246.4 B/s
txerr: 0.0 B/s
tx rate mult: 1.000
tx rate max: 1000000 B/s
rx: 0.0 B/s
rx loss: 0.0%
FTP enabled: YES, TX enabled: YES
mode: Normal
Forwarding: Off
MAVLink version: 1
transport protocol: UDP (14541, remote port: 12345)
Broadcast enabled: NO
Multicast enabled: NO
partner IP: 192.168.200.100
saluki>
```
=> mavlink: enable partner ip status print

ROMFS/px4fmu_common/init.d/CMakeLists.txt, ROMFS/px4fmu_common/init.d/airframes/1401_ssrc_holybro_x500.hil, ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt, ROMFS/px4fmu_common/init.d/rc.hitl_testing, Tools/simulation/gz/models/ssrc_standard_vtol/model_hitl.sdf, src/modules/simulation/simulator_mavlink/sitl_targets_gz-sim.cmake, test/mavsdk_tests/CMakeLists.txt, test/mavsdk_tests/configs/hitl.json, test/mavsdk_tests/configs/hitl_gz_harm.json, test/mavsdk_tests/configs/sitl_gz_harm.json, test/mavsdk_tests/mavsdk_preparing.cpp, test/mavsdk_tests/mavsdk_test_runner.py, test/mavsdk_tests/process_helper.py
Support hitl testing for the mavsdk_test_runner includes:
- Special airframe
- Adding an application to set up a test device
- Updating a test configuration
- Updating the runner to support hitl mode and gz sim
=> Added supporting hitl testing for the mavsdk_test_runner

src/drivers/lights/rgbled_is31fl3195/rgbled_is31fl3195.cpp
This enables the newer GPS stick on salukis, which don't support 100kHz i2c
=> rgbled_is31fl3195: Change default I2C frequency to 400kHz

src/modules/uxrce_dds_client/dds_topics.h.em
A fix for scenarios where the connection to the agent is cut during the connection sequence. With the proposed fixes it would appear to correctly fall back to "waiting for ping response" even if the connection is cut during writer / reader creation. Previously the false return values from the writer/reader creation would not be correctly handled and those cases would be interpreted as successes.
=> Microxrce: Added return value handling for writer and reader creation

platforms/nuttx/cmake/init.cmake
I was not able to resolve this via any cmake dependencies, so just did this...
=> Fix missing incdir tool error which came with latest NuttX

platforms/nuttx/src/px4/nxp/imx9/include/px4_arch/px4io_serial.h, platforms/nuttx/src/px4/nxp/imx9/px4io_serial/px4io_serial.cpp
Stopping tx dma in the short packet receive seems to fix the dma handle corruption issue. I have no idea why. 
- Stop also tx dma in the interrupt / short packet receive
- No need to clear the uart errors in _stop_dma, errors are cleared in uart irq
=> imx9/px4io: Cleanups

platforms/nuttx/CMakeLists.txt, platforms/nuttx/NuttX/CMakeLists.txt, platforms/nuttx/cmake/bin_romfs.cmake
An assortment of cmake script fixes for NuttX kernel mode. The highlights are in the commit messages.
=> platforms/nuttx: Fixes to NuttX CMake rules / dependencies

src/systemcmds/netconfig/netconfig.cpp
- Change drone's IP last byte to start at mav_id (1 in case of one FC)
- Use IP last byte 2 high bits to denote redundant autopilot within same drone
=> netconfig: Change IP addressing to match the new SSRC scheme

src/modules/uxrce_dds_client/uxrce_dds_client.cpp
In the uxrce udp transport init, the agent_ip string is copied without null termination, so the client may start or not, depending on what happens to be the next byte in the memory right after the _agent_ip char array.
=> uxrce_dds_client: UDP transport string null termination fix

ROMFS/px4fmu_common/init.d/airframes/1404_ssrc_standard_vtol.hil, ROMFS/px4fmu_common/init.d/airframes/1440_ssrc_skywalker_x8.hil, ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt, ROMFS/px4fmu_common/init.d/rc.hitl_testing, Tools/simulation/gz/hitl_run.sh, Tools/simulation/gz/models/ssrc_skywalker_x8/model_hitl.sdf, src/modules/simulation/simulator_mavlink/sitl_targets_gz-sim.cmake, test/mavsdk_tests/CMakeLists.txt, test/mavsdk_tests/configs/hitl_gz_harm.json, test/mavsdk_tests/configs/sitl_gz_harm.json, test/mavsdk_tests/fw_mission.plan, test/mavsdk_tests/mavsdk_test_runner.py, test/mavsdk_tests/test_fw_mission.cpp
On branch adding_hitl_testing_for_vtol_and_fw
Changes to be committed:
new file:   ROMFS/px4fmu_common/init.d/airframes/1404_ssrc_standard_vtol.hil
new file:   ROMFS/px4fmu_common/init.d/airframes/1440_ssrc_skywalker_x8.hil
new file:   Tools/simulation/gz/models/ssrc_skywalker_x8/model_hitl.sdf
new file:   test/mavsdk_tests/fw_mission.plan
new file:   test/mavsdk_tests/test_fw_mission.cpp
modified:   ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt
modified:   ROMFS/px4fmu_common/init.d/rc.hitl_testing
modified:   Tools/simulation/gz/hitl_run.sh
modified:   Tools/simulation/gz/plugins/px4-gzsim-plugins
modified:   boards/ssrc/saluki-v2
modified:   src/modules/simulation/simulator_mavlink/sitl_targets_gz-sim.cmake
modified:   test/mavsdk_tests/CMakeLists.txt
modified: …
=> Added support for hitl testing for vtol and fw

src/include/image_toc.h
This changes the MPFS TOC to have similar structure as IMX9;
- START and END addresses are indexies to the file
- There is a separate load address into where the part of the file is loaded
- It is no longer necessary to load TOC into memory
- Removed RDCT TOC entries; these don't quite work, but fixed a small issue enabling to load RDCT from a separate file later.
The current bootloader, which has been in use for some time, supports this change already. This allows cleaning up the bootloader later, by removing some MPFS specific ifdefs.
=> Update mpfs toc

src/modules/load_mon/LoadMon.cpp
Just for consistency, use the prefix for all calls.
=> LoadMon.cpp: Add px4_ prefix to enter/exit_critical() calls

platforms/nuttx/src/px4/common/cdc_acm_check.cpp, platforms/nuttx/src/px4/common/tasks.cpp
Starting a new task does not require that the scheduler is locked, this is done in nsh only because nsh uses waitpid() to wait for the task to exit and record its exit status.
The exit status does not interest us whatsoever -> remove the locking.
Also, we don't need to explicitly change a tasks priority when it is created by px4_task_spawn_cmd, as task_create() already sets the priority via nxthread_setup_scheduler().
=> platforms/nuttx: Remove unnecessary sched_lock() from task spawn logic

platforms/nuttx/src/px4/common/px4_24xxxx_mtd.c
Return -ENODEV if the device is not responding in mass erase
This fixes device not booting in case sensor board is not attached
=> px4_24xxxx_mtd.c: Fix mass erase in case device is not responding

platforms/common/include/px4_platform_common/px4_work_queue/WorkQueue.hpp, platforms/nuttx/src/px4/common/cpuload.cpp, platforms/nuttx/src/px4/common/hrt_ioctl.c, platforms/nuttx/src/px4/common/include/px4_platform/atomic_block.h, platforms/nuttx/src/px4/common/include/px4_platform/cpuload.h, platforms/nuttx/src/px4/common/print_load.cpp, platforms/nuttx/src/px4/common/px4_atomic.cpp, platforms/nuttx/src/px4/microchip/mpfs/board_reset/board_reset.cpp, platforms/nuttx/src/px4/microchip/mpfs/hrt/hrt.c, src/modules/load_mon/LoadMon.cpp
Set of patches that add SMP support to PX4
=> PX4: Add support for CONFIG_SMP=y (NuttX only)

src/drivers/imu/analog_devices/adis16470/ADIS16470.cpp
Update NuttX submodule and fix a bug in adis driver, so that it can be enabled for mpfs
=> Update nuttx for adis16470 enablement on FMU2

.github/workflows/tiiuae-pixhawk-and-saluki.yaml, .gitmodules, Tools/collect_json_files.py, Tools/compile_px4_build_info.py, Tools/fetch-fpga-files.sh, Tools/fetch-ssbl-files.sh, Tools/generate_basic_build_info.sh, Tools/px_uploader.Dockerfile, clone_public.sh
If split bootloader is available, package ssbl to build container. If split BL is not available then the full BL is compiled together in fpga and no need to include the BL file.
=> package ssbl files to px4 build container

platforms/nuttx/src/px4/microchip/mpfs/board_reset/board_reset.cpp
We cannot allow the running task to switch to another CPU after reading hartid, otherwise we will use a stale value. Fix this by reading hartid after disabling local interrupts.
=> board_reset.cpp: Hartid must be read with local interrupts disabled

Tools/decrypt_ulog.py, src/modules/logger/log_writer_file.cpp, src/modules/logger/logger.cpp
Combine encrypted log data and symmetric key into one single .ulge file.
=> Combined ulge file

.github/workflows/tiiuae-pixhawk-and-saluki.yaml
This introduces a new splitted bootloader.
From now on Saluki MPFS boards will have the First Stage BootLoader (FSBL) and the Second Stage BootLoader (SSBL).
- Refactor ...
```
```
=> Update FPGA to v4.19.0 and bootloader to v2.0.0

src/drivers/imu/analog_devices/adis16470/ADIS16470.cpp
Publishing data also in error cases may cause irregular rate at bootup, leading to wrong sample rate detection in "sensors" module
=> ADIS16470: Publish data only when there are no failures

ROMFS/CMakeLists.txt, platforms/nuttx/CMakeLists.txt, platforms/nuttx/NuttX/CMakeLists.txt
This fixes some dependencies reducing unnecessary rebuild steps from ~90 to ~10.
The remaining steps are also unnecessary but I did not figure out which rule is causing them to trigger.
=> cmake: Fix some dependencies for kernel mode build

src/modules/logger/log_writer_file.cpp, src/modules/logger/log_writer_file.h
The init_logfile_encryption() function is called after the buffer's start_log() is called and file is already opened.
=> logger: fix file open issue if crypto algorithm is disabled

ROMFS/px4fmu_common/init.d/airframes/4421_ssrc_skywalker
1. Updated CA parameters as the setup is always same in all builds. 
3. Removed the line which disables internal mag. 
4. Added battery parameters.
5. Changed ASPD_DO_CHECKS as currently the Saluki has to be rebooted after landing as bit 3: Load factor check (triggers if measurement is below stall speed) triggers airspeed failure after each landing.
6. Changed the loiter radius as it was too tight.
7. Removed the parameter that required a takeoff and a landing pattern for a mission.
8. Changed launch detection acceleration value to 3 from 0.
9. Added some parameters for more successful takeoffs.
=> Update 4421_ssrc_skywalker airframe parameters

src/drivers/imu/analog_devices/adis16470/ADIS16470.cpp, src/drivers/imu/analog_devices/adis16470/ADIS16470.hpp
Fix various issues in ADIS16470 initialization
=> Adis16470 stability fixes

Tools/run_docker_hitl_gzsim_mavsdk_server.sh, packaging/Dockerfile.hitl_gzsim_mavsdk, packaging/build_px4_hitl_gzsim_mavsdk.sh, packaging/entrypoint_hitl_gzsim_mavsdk.sh
Added Dockerfile for HITL simulation and MAVSDK testing of FC, along with a helper script for easier container usage.
- The primary target device is SalukiV2, with support for SalukiV3 in a reduced configuration (FC only).
- Successfully tested with SalukiV2.
Changes to be committed:
new file:   Tools/run_docker_hitl_gzsim_mavsdk_server.sh
new file:   packaging/entrypoint_hitl_gzsim_mavsdk.sh
new file:   packaging/Dockerfile.hitl_gzsim_mavsdk
new file:   packaging/build_px4_hitl_gzsim_mavsdk.sh
Usage:
```
./Tools/run_docker_hitl_gzsim_mavsdk_server.sh <docker_image> <script_and_arguments>
```
Run HITL simulation:
```
./Tools/run_docker_hitl_gzsim_mavsdk_server.sh <docker_image> ./Tools/simulation/gz/hitl_run.sh ssrc_holybro_x500/model_hitl.sdf
```
Run MAVSDK tests:
``` …
```
=> Adding the mavsdk docker image for tesing FC in sitl and hitl mode

src/modules/load_mon/LoadMon.cpp, src/modules/load_mon/LoadMon.hpp
This fixes the cpuload topic, calculates an average CPU idle time from all CPUs and uses this to estimate application CPU load (1-idle = load).
=> LoadMon.cpp: Support for CONFIG_SMP=y

src/drivers/sw_crypto/crypto.c, src/lib/crypto/CMakeLists.txt, src/modules/logger/log_writer_file.cpp, src/modules/logger/log_writer_file.h
Saluki-NXP FCOTA support
- Xchacha20 decrypt support to sw_crypto
- use Xchacha20 cipher instead of AES (not currently supported in nxp sw_crypto)
- sw_crypto Xchacha20 supporting both MAC and non-MAC usage.
- Logger file encrypt call modified to use non-mac version in sw_crypto case (mac as null)
- Added RSA signature verification support into sw_crypto
=> FCOTA suppor for Saluki-NXP

.gitmodules
This reverts commit e3a854d517a7182150a1d02ecac21c2278f4a9c9.
This commit was made long time ago when there was some issues in remote repository and submodule fetch failed. That broke the CI building, so the temporary quick fix was to remove the submodule from px4-firmware build.
Seems that this alternative simulator is used by some parties, so it should be re-enabled.
It is not causing any issues anymore in CI, so the temporary removal commit can be reverted.
=> Revert "Remove failing submodule: Tools/simulation/jsbsim/jsbsim_bridge"

ssrc_config/config_indoor.txt
Removed obsolete LED definitions from config_indoor.txt
=> Removed LED definitions from ssrc_config/config_indoor.txt

platforms/nuttx/src/px4/nxp/imx9/board_reset/board_reset.cpp
PMIC WDOG_B pin is unused in current HW design.
Related configuration bits (WDOG_B_CFG) from PMIC RESET_CTRL register are borrowed for bootmode reason delivery.
boot normally: register has power on value
stay in bootloader: WDOG_B_CFG 11b
**NOTE**: I've observed the device goes occasionally to NXP flash / serial download mode after sending cold reset request to PMIC. The reason is unknown.
Corresponding bootloader functionality is needed for the complete functionality.
The full set of PRs:
* https://github.com/tiiuae/nuttx/pull/348
* https://github.com/tiiuae/saluki_bootloader_v2/pull/175
* https://github.com/tiiuae/px4_boards_ssrc/pull/77
* https://github.com/tiiuae/px4-firmware/pull/886
=> [imx9 boot reason 4/4] Use PMIC registers to store bootmode information

.github/workflows/tiiuae-pixhawk-and-saluki.yaml
UAE jfrog token has expired so disabling this step until we receive new token.
This is to avoid all builds failing. Binaries are available in docker also for UAE
=> disable uae jfrog upload

platforms/nuttx/src/px4/common/cpuload.cpp
In task restart case, the sched note is not stopped before started again; in this case the tcb already exists in the hash table. Check this before growing the hash table size.
This was found in ostest, where hash table size suddenly explodes.
=> px4/common/cpuload: Manage task restart in cpuload hash table

platforms/common/uORB/uORB.cpp
- Update rust_px4_nuttx lib: Relocate the rust bindings file generation output from source folder to cmake target build folder.
- Update boards/ssrc/common for dac_get/put support required by updated rust_px4_nuttx library.
- Cleanup debug print from uOrb interface
=> Rust nuttx binding change

platforms/common/include/px4_platform_common/crypto_algorithms.h, src/drivers/sw_crypto/crypto.c, src/lib/crypto/CMakeLists.txt, src/lib/crypto/libtomcrypt_wrappers.c
Add sw_crypto support for ECDSA secp384r1 signature verification for Device Assembly Card authentication
=> SW Crypto: P384 support

platforms/nuttx/src/px4/microchip/mpfs/px4io_serial/px4io_serial.cpp
Otherwise the connection to the IO board won't work.
Needs updates to FPGA and bootloader
=> px4io_serial.cpp: Release FPGA serial from reset

src/modules/mavlink/mavlink_main.cpp, src/modules/mavlink/mavlink_messages.cpp, src/modules/mavlink/mavlink_receiver.cpp, src/modules/mavlink/streams/TUNNEL.hpp
For AssemblyAgent implementation the Mavlink Tunnel messages shall be also sent out. To separate inwards and outwards messages the mavlink_tunnel.target_system field is checked in both mavlink receiver and stream handling.
=> Mavlink: Add new stream TUNNEL

platforms/nuttx/src/px4/microchip/mpfs/board_reset/board_reset.cpp
There is a rare race condition with board_reset with SMP; the CPU might change when we are setting up the following SMP call to other CPUs. The logic in board_reset fails if this happens.
Prevent the race by locking the current task's CPU.
=> board_reset.cpp: Fix race condition with SMP

platforms/nuttx/NuttX/CMakeLists.txt
Currently the nuttx app build strips all debug symbols by default, and places them into BINDIR_DEBUG.
Our own build system does it as well, but it expects the un-stripped binaries to be in the /bin folder.
Fix this by putting the debug binaries into /bin so our own toolchain still works as before.
=> build_kernel: Preserve debug symbols for nuttx app binaries

platforms/nuttx/NuttX/CMakeLists.txt, platforms/nuttx/NuttX/extern/.gitignore, platforms/nuttx/NuttX/extern/apps/CMakeLists.txt, platforms/nuttx/NuttX/extern/apps/Make.defs, platforms/nuttx/NuttX/extern/apps/Makefile, platforms/nuttx/cmake/init.cmake
This allows us to include external, out-of-tree NuttX Apps as git submodules. It does so by linking the directory platforms/nuttx/NuttX/extern/apps to platforms/nuttx/NuttX/apps/external.
The rationale is I've been developing a little attestation daemon as a plain NuttX app that I would like to contribute to px4-firmware as a private git repo.
If you think we should only have apps as PX4 modules in px4-firmware, please feel free to drop this.
NuttX reference: https://nuttx.apache.org/docs/latest/guides/building_nuttx_with_app_out_of_src_tree.html#special-apps-external-directory
```
Support for external, out-of-tree NuttX Apps
```
We can also include git submodule apps as PX4 modules (as we already do for some) but this might make sense for apps that do not need/use PX4 …
=> px4-cmake: Add support for external NuttX apps

.gitmodules, clone_public.sh
Saluki-NXP px4-crypto has currently keycache which prevents to use keystore slots above index 15 due to direct mapping betwen keyslots of keycache and actual keystore. To remove that restrictions the new keycache implementation from pfsoc_crypto is taken into use for NXP also. The new keyscache implementation has separate index mappings between cache and keystore allowng to use the whole keystore index range.
As part of the new keycache integration the NXP crypto driver has moved to the private pfsoc_crypto repository, basically new crypto_imx9 driver has been created by deriving the driver code from upstream sw_crypto driver and integrating the new keycache into it. Also the pfsoc_crypto submodule has been renamed to ssrc_crypto as it now contains also NXP driver. Similar renaming is …
=> Improved keycache for Saluki-NXP px4-crypto (pfsoc_crypto rename ssrc_crypto)

.gitmodules, Makefile, clone_public.sh, packaging/build_px4fw.sh, platforms/nuttx/NuttX/CMakeLists.txt, platforms/nuttx/NuttX/extern/apps/CMakeLists.txt, platforms/nuttx/NuttX/extern/apps/Make.defs
This brings in the attestation agent and enables it by default, but does not start it. The command is `aa` and it needs manual invocation for now. I guess it can go into some init.rc file once it's ready to be used.
Right now it has some dependencies to DAC and provisioning CA. With this PR is usable with test data and [demo peers](https://github.com/tiiuae/attestation-demo) as described in [nxp93-attestation's README](https://github.com/tiiuae/nxp93-attestation?tab=readme-ov-file#demo-run).
The latter repo is the main addition this PR brings. It adds a "drop-in" external nuttx app (not PX4 app, not yet at least) providing the `aa` command.
This PR requires also:
- https://github.com/tiiuae/saluki-nxp93/pull/45
- https://github.com/tiiuae/saluki_bootloader_v2/pull/200
- NuttX branch …
=> Add NXP93 attestation support (manual activation)

src/modules/mavlink/mavlink_log_handler.cpp
MavlinkLogHandler is constructed before the parent Mavlink object, so the MavlinkLogHandler constructor can't read any MAvlink object states because it is not yet constructed and variables are uninitialized.
is_crit_act_enabled() is now called when the first log_request_list msg is received.
=> mavlink: critical action enable check fixed

.github/workflows/tiiuae-pixhawk-and-saluki.yaml
This updates NuttX and saluki-v2, v3 and pi (fmu2) defconfigs to enable i2c extension on all i2c buses.
=> Integrate mpfs i2c fifo

platforms/nuttx/CMakeLists.txt, platforms/nuttx/NuttX/CMakeLists.txt, platforms/nuttx/NuttX/Make.defs.in
Submodule update for saluki-nxp93 was not done properly earlier, when fully-linked executables was enabled. This corrects the issue.
=> Update boards/ssrc for fully-linked executables for CONFIG_BUILD_KERNEL
