- msg/tools/uorb_rtps_message_ids.yaml
Set sensor_gps messages to be received by PX4 via micrortps bridge
> Receive sensorGps rtps messages

- msg/tools/uorb_rtps_message_ids.yaml
Add vehicle_land_detected and vehicle_local_position into the micrortps_bridge publisher list
> micrortps bridge: send land_detection and local_position

- ROMFS/px4fmu_common/init.d-posix/airframes/4400_ssrc_fog_x
- ROMFS/px4fmu_common/init.d/airframes/4400_ssrc_fog_x
- msg/tools/uorb_rtps_message_ids.yaml
Increase TEL1 baudrate to 3M for ssrc_fog_x
> Inc tel1 baudrate

- msg/tools/uorb_rtps_message_ids.yaml
Add sensor_mag sending into micrortps_bridge conf
> micrortps bridge: send sensor_mag messages

- ROMFS/px4fmu_common/init.d/airframes/4400_ssrc_fog_x
- Set TELEM1 baudrate to 1M
- Enable rangefinder
- Enable leds
- Set some battery defaults
How was it tested? What cases were covered? Logs uploaded to …
> Fix some default paramters for ssrc_fog_x

- src/drivers/distance_sensor/ll40ls/LidarLiteI2C.cpp
- src/modules/micrortps_bridge/micrortps_client/microRTPS_client_main.cpp
- src/modules/navigator/navigator_main.cpp
> Fix ll40ls

- msg/tools/uorb_rtps_message_ids.yaml
@jlaitine please check if this is correct. I don't know yet how to flush firmware on my micro PX4. 
At least this compiles...
> Enable GPS output

- src/drivers/protocol_splitter/protocol_splitter.cpp
Parenthesis fix for protocol_splitter 4-byte header change
> fix parenthesis

- .github/workflows/tiiuae-pixhawk.yaml
- .github/workflows/tiiuae-sitl.yaml
> add tiiuae CI workflows

- .github/workflows/tiiuae-pixhawk.yaml
- .github/workflows/tiiuae-sitl.yaml
> enable CI build promotion

- .github/workflows/tiiuae-pixhawk.yaml
- .github/workflows/tiiuae-sitl.yaml
> upload px4-firmware and px4-fwupdater into separate builds

- .github/workflows/tiiuae-gzebo-data.yaml
- .github/workflows/tiiuae-pixhawk.yaml
- .github/workflows/tiiuae-sitl.yaml
> Gazebo data workflow

- msg/tools/uorb_rtps_message_ids.yaml
Send baro and distance sensor rtps messages for F4F nav stack.
Corresponding PR in px4_ros_com: https://github.com/tiiuae/px4_ros_com/pull/14
> send baro and distance sensor

- msg/templates/uorb_microcdr/msg.cpp.em
- msg/templates/urtps/RtpsTopics.cpp.em
- msg/templates/urtps/RtpsTopics.h.em
- msg/templates/urtps/microRTPS_agent.cpp.em
Deliver only time delta from original TS to the time message is sent. In receiving end add current time to the received delta. In addition to that the micrortps_agent side adds the transmission delay.
> urtps: Simplified timesync

- .github/workflows/tiiuae-sitl.yaml
> trigger fog-drone build

- boards/ssrc/saluki/default.cmake
- boards/ssrc/saluki/init/rc.board_sensors
- boards/ssrc/saluki/src/i2c.cpp
> saluki board: Enable PX4 GPS module magnetometer and LED controller

- boards/px4/fmu-v5/src/stm32_userspace.c
> Fix protected build

- ssrc_config/HIL/config.txt
- ssrc_config/indoor_lighthouse/config.txt
Add 'Env' tag into config.txt files for indoor and hitl to be able to detect version with automatic changer script
> Add env tag into config.txt files

- boards/ssrc/saluki/init/rc.board_sensors
> saluki board: Enable ll40ls and fix icm20649 SPI speed

- .github/workflows/tiiuae-pixhawk.yaml
- .github/workflows/tiiuae-sitl.yaml
- .gitmodules
Adds initial support for Saluki v1 board
> Add Saluki v1 submodule

- platforms/nuttx/src/px4/microchip/mpfs/version/board_mcu_version.c
Updates also saluki and nuttx submodules
> mpfs: Support for HW version multipurpose pins

- .github/workflows/tiiuae-pixhawk.yaml
add saluki build to CI workflow. Upload saluki build to Artifactory.
**Additional …
> Build PX4 Autopilot for Saluki

- ROMFS/px4fmu_common/init.d/airframes/4400_ssrc_fog_x
Update airframe configuration according to the new px4
How was it tested? What cases were covered? Logs uploaded to https://review.px4.io/ and screenshots of the …
> Correct default parameters

- ROMFS/px4fmu_common/init.d/airframes/4400_ssrc_fog_x
> Correct setting of default paramters for 4400_ssrc_fog_x airframe

- ROMFS/px4fmu_common/init.d/airframes/4400_ssrc_fog_x
Also correct comments in airframe file
> 4400_ssrc_fog_x: Change default parameters BAT_ -> BAT1_

- msg/tools/urtps_bridge_topics.yaml
Add home_position to rtps send list
> Add home_position into rtps send list

- build.sh
- packaging/Dockerfile.build_pixhawk
- packaging/Dockerfile.build_saluki
- packaging/Dockerfile.build_sitl
> fix versions in binary builds

- .github/workflows/tiiuae-pixhawk.yaml
- build.sh
- packaging/Dockerfile.build_pixhawk
- packaging/Dockerfile.build_px4fwupdater
- packaging/Dockerfile.build_saluki
Move version adding to binaries into the builder container side
> Rename binaries in builder side

- platforms/common/include/px4_platform_common/px4_work_queue/WorkQueueManager.hpp
- src/modules/navigator/navigator_main.cpp
> Increase navigator and uart wq stacks

- src/drivers/protocol_splitter/protocol_splitter.cpp
> Fix protocol splitter again

- ssrc_config/indoor_lighthouse/config.txt
> Disable log encryption for indoor flights

- packaging/Dockerfile.build_env
Fix broken build because of foonathan package being downloaded from artifactory.
> Avoid using foonathan package from artifactory

- boards/px4/fmu-v5x/init/rc.board_mavlink
- ssrc_config/HIL/ethernet/config.txt
Separate ssrc HITL config.txt file added for ethernet connection
FTP enabled for ethernet mavlink connection to be able to use all the fogsw tools from mission-computer side
> Hitl setup for pixhawk5x

- boards/ssrc/icicle/src/CMakeLists.txt
- boards/ssrc/icicle/src/board_config.h
- boards/ssrc/icicle/src/mpfs_domain.c
SeL4 boots from hart 1, Linux hart 3 & 4
Signed-off-by: Jouni Ukkonen <jouni.ukkonen@unikie.com>
How was it tested? What cases were covered? Logs uploaded to https://review.px4.io/ and screenshots of the important …
> Domain init support for icicle board

- boards/ssrc/icicle/src/init.c
- boards/ssrc/icicle/src/mpfs_spinor.c
- platforms/nuttx/src/px4/microchip/microchip_common/include/px4_arch/spi_hw_description.h
- platforms/nuttx/src/px4/microchip/mpfs/include/px4_arch/spi_hw_description.h
Fix build and init errors when setting CONFIG_MTD_M25P=n
> Fix mtd m25p dep

- platforms/nuttx/src/px4/common/usr_hrt.cpp
Fix a few issues with user hrt module.
> usr_hrt: Fix a few minor issues

- platforms/nuttx/src/px4/microchip/mpfs/hrt/hrt.c
There was a bug found in HRT. It doesn't return the accurate timestamp, but instead the timestamp at the time when the base time was last updated. This fixes the issue.
Also optimize the HRT slightly to avoid one extra register read.
> Fix saluki hrt

- platforms/nuttx/src/px4/microchip/mpfs/include/px4_arch/micro_hal.h
Enable sensor DRDY signal to get rid of sensor errors (fifo overflows etc)
> Saluki enable sensors drdy

- boards/px4/fmu-v5x/src/board_config.h
- platforms/common/board_common.c
- platforms/nuttx/src/px4/common/board_ctrl.c
Fix VBUS detection logic from active-high to active-low
> Dp 3432 usb cable not detected

- platforms/nuttx/src/bootloader/microchip/mpfs/main.c
Tiny fix, don't attempt eMMC write if the media is not mounted / open
> mpfs/bootloader: Don't attempt eMMC write, if is not open

- ssrc_config/config_indoor.txt
Update indoor config according to currently used setup
> Update indoor flight config

- .github/workflows/tiiuae-sitl.yaml
- ROMFS/px4fmu_common/init.d-posix/px4-rc.params
- packaging/Dockerfile.sitl
- ssrc_config/config_indoor_sim.txt
ssrc_config files copied into tii-px4-sitl container image.
Configuration can be selected by env variable SSRC_CONFIG.
E.g.
SSRC_CONFIG=indoor
=> source /ssrc_config/config_indoor.txt file for indoor flying parameters.
> Sitl config txt support

- platforms/nuttx/src/px4/microchip/microchip_common/adc/CMakeLists.txt
- platforms/nuttx/src/px4/microchip/microchip_common/adc/adc.cpp
- platforms/nuttx/src/px4/microchip/mpfs/include/px4_arch/adc.h
- src/drivers/adc/board_adc/ADC.cpp
This fixes the system_power reporting for saluki
> Fix power input valid for saluki

- Tools/px_uploader.entrypoint
- boards/px4/fmu-v5x/init/rc.board_mavlink
px_uploader shall send PX4 reboot command directly to FC IP address.
px4-post-update-init tool arguments updated
> fwupdater: Fix eth connection of updater to point directly to FC

- boards/px4/fmu-v5/src/toc.c
- boards/px4/fmu-v5x/src/toc.c
- boards/ssrc/icicle/src/toc.c
The signature end address is incorrect
> Fix RD certificate signature location in ToC

- msg/tools/urtps_bridge_topics.yaml
_gps_inject_data_ Topic is exposed on microRTPS bridge enabling the use of RTK base corrections
> RTK Correction topic exposed on microRTPS

- boards/px4/fmu-v5/nuttx-config/scripts/script.ld
- boards/px4/fmu-v5/nuttx-config/scripts/toc.ld
- boards/px4/fmu-v5/src/toc.c
- boards/px4/fmu-v5x/nuttx-config/scripts/script.ld
- boards/px4/fmu-v5x/nuttx-config/scripts/toc.ld
- boards/px4/fmu-v5x/src/toc.c
- platforms/nuttx/CMakeLists.txt
- platforms/nuttx/src/bootloader/common/bl.c
- platforms/nuttx/src/bootloader/common/crypto.c
- platforms/nuttx/src/bootloader/common/image_toc.c
- platforms/nuttx/src/bootloader/microchip/mpfs/main.c
- platforms/nuttx/toc/CMakeLists.txt
- platforms/nuttx/toc/fw_image.c
- src/include/image_toc.h
Depends on: https://github.com/tiiuae/saluki-v1/pull/35
> Move ToC to the beginning of the firmware image

- platforms/nuttx/src/px4/common/px4_userspace_init.cpp
- platforms/nuttx/src/px4/common/usr_hrt.cpp
- src/modules/dataman/dataman.cpp
Backport a few fixes from upstream
> misc: Pick a few fixes from upstream

- platforms/nuttx/src/px4/common/px4_layer.cmake
Fixes build error related to board_read_VBUS_state
> Fix linkage of board_read_VBUS_state

- Tools/px_uploader.Dockerfile
- Tools/px_uploader.entrypoint
> Disable PX4 post init configuration

- platforms/nuttx/src/bootloader/common/bl.c
- platforms/nuttx/src/bootloader/common/crypto.c
- platforms/nuttx/src/bootloader/common/crypto.h
- platforms/nuttx/src/bootloader/common/image_toc.c
- platforms/nuttx/src/bootloader/microchip/mpfs/main.c
- src/include/image_toc.h
Backport changes from Bootloader repo to minimize source code delta between them
> bootloader: Backport changes from bootloader repo

- .github/workflows/tiiuae-pixhawk.yaml
Artifactory upload is broken for saluki-v2 packages:
https://github.com/tiiuae/px4-firmware/actions/runs/3148941753/jobs/5120238326
> Fix artifactory upload for saluki-v2 packages

- platforms/common/include/px4_platform_common/px4_work_queue/WorkQueue.hpp
- platforms/nuttx/src/px4/common/CMakeLists.txt
- platforms/nuttx/src/px4/common/include/px4_platform/atomic_block.h
- platforms/nuttx/src/px4/common/px4_atomic.cpp
- platforms/nuttx/src/px4/common/px4_protected_layers.cmake
- platforms/nuttx/src/px4/common/usr_atomic.cpp
Pending in upstream: https://github.com/PX4/PX4-Autopilot/pull/20170
Merge for local testing
> px4_work_queue: Fix work queue atomic sections for NuttX user space

- packaging/build_saluki.sh
Add protected build to the build targets, so it can be tested with official builds
> build_saluki.sh: Add protected build for saluki-v1

- boards/px4/fmu-v5/nuttx-config/scripts/toc.ld
- boards/px4/fmu-v5x/nuttx-config/scripts/toc.ld
Detect firmware area overflow if the signature does not fit
> boards/xx/toc: Make sure there is room for the firmware signature

- ssrc_config/config_hitl_eth.txt
Fix mavlink udp start command
Remove indoor configs
> config_hitl_eth.txt adjustment

- .github/workflows/tiiuae-pixhawk-artifact-publish.yaml
Created a new workflow file "tiiuae-pixhawk-artifact-publish.yaml" by copying "tiiuae-pixhawk.yaml". 
Made necessary changes in the newly created workflow file for publishing artifacts to SSRC uae jfrog artifactory and pushing docker images to SSRC uae jfrog container registry.
> SSRC uae artifactory configurations

- platforms/nuttx/src/bootloader/microchip/mpfs/main.c
The debugger reset reason is giving random values at high temperaturs in power-on-reset.
Change the bootloader logic to first check if the device has been cold-booted and only after that check the debugger reset reason. Use the fabric reset reason to detect POR, since that is only set at power-on. Other bits don't give the correct status, the specs are buggy.
> bootloader/microchip/mpfs/main.c: Fix POR reset

- platforms/nuttx/src/px4/common/hrt_ioctl.c
This fixes the commit 827e8b19991a5bd4f6ba0e4a81855957091c8ae6: Fix usr_hrt to work also in CONFIG_BUILD_KERNEL, which caused kernel side memory leaks when hrt timers are re-scheduled
Add another queue to the usr_hrt iterface, which mirrors the actual drivers "callout_queue", to keep track on the queued hrt events.
Also clean up some unnecessary initializations and protect the queues in hrt_cancel() call.
E.g. For this use case I …
> Fix memory leaks from the usr_hrt driver

- src/drivers/pwm_esc/pwm_esc.cpp
Cleanups for pwm_esc driver
- Add "stop" command
- Remove exit(), errx() etc. to make it behave also in kernel side
- Remove unnecessary #includes
- Some other small cleanups
> sr/drivers/pwm_esc: Add support for stopping the driver

- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
- upload to cloud instance instead of artifactory.ssrc.fi
- allow running github action manually
> DP-4201 upload to artifactory cloud instance

- platforms/nuttx/src/bootloader/microchip/mpfs/main.c
Fix for "Only one CPU is used in Saluki HardenedOS" bug. Sel4 removed from Hart 1 and taken into Linux use.
https://ssrc.atlassian.net/browse/DP-3816
If SMP is used on Linux, the primary core (Hart 3) will boot the secondary cores (Hart 1 and 4), so they should not be booted in the bootloader.
> Only one CPU is used in Saluki HardenedOS fix. Sel4 removed

- src/modules/microdds_client/dds_topics.yaml
Fix gps related topic names to be input topics
> Fix sensor_gps and gps_inject_data uxrce topic names

- platforms/nuttx/src/px4/common/px4_protected_layers.cmake
- platforms/nuttx/src/px4/common/px4_userspace_init.cpp
- src/systemcmds/mtd/Kconfig
Add commits from master -> main
Original:
https://github.com/tiiuae/px4-firmware/pull/278
> Add missing commits after rebase and change to main-branch

- platforms/nuttx/src/px4/common/hrt_ioctl.c
- platforms/nuttx/src/px4/common/usr_hrt.cpp
- src/drivers/drv_hrt.h
Fixes several issues with user HRT, highlights in commit messages
> usr_hrt: Fix several issues with the ioctl interface (usage and internal errors)

- src/drivers/pwm_esc/Kconfig
- src/drivers/pwm_esc/pwm_esc.cpp
This fixes the escs not working in protected build.
Also fixes some high CPU load issue (lowers CPU consumption approx. by 10%).
> Fix pwm esc for protected

- platforms/nuttx/src/px4/common/usr_hrt.cpp
- platforms/nuttx/src/px4/microchip/mpfs/hrt/hrt.c
- platforms/nuttx/src/px4/microchip/mpfs/include/px4_arch/micro_hal.h
So I did this. All by myself. Sorry about it.
It is (partially) protected build specific, but works and is super light compared to the old implementation.
Solves the logger being too heavy in protected build ( and implements https://ssrc.atlassian.net/browse/DP-4891)
It also fixes https://ssrc.atlassian.net/browse/DP-3829 for all build types
> Optimize hrt

- build_sitl.sh
- packaging/Dockerfile.build_env_sitl
- packaging/Dockerfile.sitl
- packaging/build_px4_sitl.sh
- packaging/build_px4fw.sh
- packaging/entrypoint.sh
- tasks.py
Use humble version of ROS2 libraries to generate ROS2 messages and build SITL
> Humble main

- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
Enable to run saluki build jobs also for workflow_dispatch case.
> Enable manual run for saluki targets

- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
- platforms/nuttx/src/bootloader/microchip/mpfs/main.c
This is the second part of enabling Athena crypto co-processor for saluki-v2 onwards
The actual changes are in submodules
> Enable crypto

- .gitmodules
- clone_public.sh
- platforms/common/include/px4_platform_common/crypto_backend.h
- platforms/nuttx/src/bootloader/common/bl.c
- platforms/nuttx/src/px4/common/nuttx_random.c
- src/drivers/sw_crypto/crypto.c
This fixes issues with double-initialization of Athena crypto and adds the pfsoc_keystore (PolarFire sNVM secure key storage support) into build.
Athena or secure key storage are not enabled yet for saluki with this PR
> Add pfsoc keystore and crypto fixes

- ROMFS/px4fmu_common/init.d/rcS
> Mission computer lite ip change

- src/modules/microdds_client/Kconfig
> modules/microdds_client: Put microdds client to user space

- .github/workflows/tiiuae-sitl.yaml
artifactory path fix: gen-public-local --> ssrc-gen-public-local
> Fix sitl cloud artifactory push paths

- platforms/nuttx/src/px4/common/hrt_ioctl.c
Make sure the same entry is not put into inflight queue twice.
Why? Because the list is a singly linked list, and posting the same entry twice would create a queue loop which soft locks the entire system.
When does this happen ? If the client thread cannot read the event out in time, a new event can arrive. The same handle is used for HRT_CALL_EVERY and in this case double booking can happen.
> hrt_ioctl: Do not double post same entry to inflight queue

- boards/ssrc/icicle/src/bootloader_main.c
- platforms/nuttx/src/px4/common/hrt_ioctl.c
- platforms/nuttx/src/px4/common/usr_hrt.cpp
- src/drivers/rover_interface/RoverInterface.cpp
- src/drivers/rover_interface/RoverInterface.hpp
- src/drivers/rover_interface/scout_sdk/include/scout_sdk/CAN/SocketCAN.hpp
- src/drivers/rover_interface/scout_sdk/include/scout_sdk/CAN/can_frame.h
- src/drivers/rover_interface/scout_sdk/include/scout_sdk/ScoutRobot.hpp
- src/drivers/rover_interface/scout_sdk/include/scout_sdk/Utilities.hpp
- src/drivers/rover_interface/scout_sdk/include/scout_sdk/agilex_protocol/agilex_protocol_v2.h
- src/drivers/rover_interface/scout_sdk/include/scout_sdk/agilex_protocol/agilex_protocol_v2_parser.hpp
- src/drivers/rover_interface/scout_sdk/src/CAN/SocketCAN.cpp
- src/drivers/rover_interface/scout_sdk/src/ScoutRobot.cpp
- src/drivers/rover_interface/scout_sdk/src/Utilities.cpp
- src/drivers/rover_interface/scout_sdk/src/agilex_protocol/agilex_msg_parser_v2.c
- src/drivers/uavcan/uavcan_main.cpp
- src/modules/microdds_client/microdds_client.cpp
This fixes the formatting issues currently in our main branch
After merging this, @gautham-tii will enable format checking for PR:s in the CI, so that formatting errors won't go through any more..
> Fix formatting

- platforms/nuttx/src/bootloader/microchip/mpfs/main.c
- platforms/nuttx/src/px4/microchip/mpfs/include/px4_arch/hw_description.h
- platforms/nuttx/src/px4/microchip/mpfs/include/px4_arch/micro_hal.h
- platforms/nuttx/src/px4/microchip/mpfs/include/px4_arch/spi_hw_description.h
> platforms/mpfs: Add support for CoreSPI, CoreI2C and FPGA Uart

- platforms/nuttx/src/px4/microchip/microchip_common/include/px4_arch/px4io_serial.h
- platforms/nuttx/src/px4/microchip/mpfs/include/px4_arch/px4io_serial.h
- platforms/nuttx/src/px4/microchip/mpfs/px4io_serial/CMakeLists.txt
- platforms/nuttx/src/px4/microchip/mpfs/px4io_serial/px4io_serial.cpp
- src/drivers/pwm_esc/CMakeLists.txt
- src/drivers/pwm_esc/module.yaml
- src/drivers/pwm_esc/pwm_esc.cpp
- src/drivers/px4io/px4io.cpp
Enable px4io
I will still optimize the IRQ load by using rx buffer threshold interrupt, when the threshold is freely settable in the fpga uart block
> Enable px4io on pi 2

- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
- .github/workflows/tiiuae-sitl-tests.yml
- .github/workflows/tiiuae-sitl.yaml
Some tiiuae organisation level change has caused some projects to fail pushing to ghcr
> allow workflow push packages

- ROMFS/px4fmu_common/init.d/rc.logging
- platforms/nuttx/src/bootloader/microchip/mpfs/main.c
- OpenSBI reloc backported
- Support for mavlink logging for amp
> New bsp wip sbi reloc

- platforms/nuttx/src/px4/common/px4_init.cpp
Bug found in inspection (jira DP-6338)
> Fix mount procfs return value check

- ROMFS/px4fmu_common/init.d/airframes/50005_ssrc_scout_mini_rover
make sure uavcan is not used for UGV
> Update 50005_ssrc_scout_mini_rover: disable UAVCAN

- .github/workflows/tiiuae-coverity-scan-image.yaml
- .github/workflows/tiiuae-coverity-scan.yaml
- packaging/Dockerfile.coverity
- packaging/coverity.yaml
- packaging/entrypoint_coverity.sh
Run coverity scan for PX4. It is rather heavy process so this is ran on self-hosted PC
- tiiuae-coverity-scan-image.yaml creates coverity scan container (ran manually as needed)
- tiiuae-coverity-scan.yaml runs the actual scan
> Coverity scan

- src/systemcmds/uorb/uORBDeviceMaster.cpp
Fix a few issues found in coverity scan
> Uorb fix small resource leak

- ROMFS/CMakeLists.txt
Fix dependency for rc.sysinit generation
> ROMFS/CMakeLists.txt: Fix dependency for rc.sysinit 

- platforms/common/uORB/uORBDeviceNode.cpp
- src/modules/microdds_client/dds_topics.h.em
- src/modules/microdds_client/generate_dds_topics.py
- src/modules/microdds_client/microdds_client.cpp
uxrce topic update rate is too slow. e.g. VehicleOdometry uOrb is updated 100Hz freq in PX4, but the ROS2 topic published by microxrce-dds-agent is updated ~50Hz. Problem is that microdds_client update loop is using px4_usleep to read uorbs every 1ms, but due to long system tick period, the wait time is about 10-20ms.
Changed microdds_client update loop to use px4_poll for subscribed uorbs instead of waiting with px4_usleep(1000) and read current values after that. The update rate can be defined in subscription, so the minimum wait time can be set to same 1ms with that feature. Also the rate limiting feature for singleSoc (amp) case is now changed to utilize this same subscription wait feature.
Simpler solution would have been to reduce system tick count from 10ms to 1ms, but that …
> Dp 6657 uxrce pub rate fix

- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
- .gitmodules
- build.sh
- src/drivers/adc/ads1115/ADS1115.h
This adds saluki-v3 support.
Submodule updates still remaining after all changes have been merged to those
> Add saluki v3

- platforms/common/include/px4_platform_common/tasks.h
- platforms/nuttx/src/px4/common/cdc_acm_check.cpp
- platforms/nuttx/src/px4/common/tasks.cpp
- src/modules/mavlink/CMakeLists.txt
- src/modules/mavlink/mavlink_shell.cpp
- src/modules/mavlink/mavlink_shell_main.cpp
What is missing from rebased main
> Mavlink fix picks

- build.sh
Makes analyzing core dumps a whole lot easier
> build.sh: Add kernel mode .elf file as saved artifact

- cmake/gtest/px4_add_gtest.cmake
- platforms/common/apps.cpp.in
- platforms/common/uORB/uORB_tests/uORBTest_UnitTest.hpp
- src/lib/controllib/controllib_test/controllib_test_main.cpp
- src/modules/navigator/MissionFeasibility/FeasibilityCheckerTest.cpp
> Fix make tests

- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
> Updated FPGA to sha-4230961

- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
This is ported from px4-firmware-fc-only
> input to choose FPGA version while manually triggering build

- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
- generate inputs and outputs for the build process
- generate instructions how to get the build output downloaded from docker container
> print build input and output containers

- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
> Updated fpga to sha-b7e842d

- src/systemcmds/uorb/uORBDeviceMaster.cpp
Fix a memory leak in uorb systemcmd
I found this fix lying around, maybe it fixes the https://ssrc.atlassian.net/browse/DP-7850
> src/systemcmds/uorb: Map every uorb instance just once

- src/lib/perf/perf_counter.cpp
Instead of using a global perf list (that does not work in protected builds) allocate the perf objects into shared memory.
> lib/perf: Implement perf on top of shmfs

- .github/workflows/tiiuae-sitl-gzsim.yaml
- ROMFS/px4fmu_common/init.d/rc.rover_apps
- packaging/Dockerfile.sitl_gzsim
- src/modules/simulation/gz_bridge/CMakeLists.txt
- src/modules/simulation/gz_bridge/GZMixingInterfaceESC.hpp
- migrate to Gazebo Harmonic
- workflow: add px4 sitl gzsim docker image build and push
> gzsim SITL update

- .github/workflows/tiiuae-pixhawk-and-saluki-builder.yaml
- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
- upload/download artifacts v3 -> v4
- jfrog-cli v3 -> v4
- remove cloud artifactory upload
- new uae artifactory doesn't have deploy rights so just copy the file without build publish
> update github actions

- platforms/common/include/px4_platform_common/crypto_backend.h
- platforms/nuttx/src/px4/common/include/px4_platform/board_ctrl.h
- src/drivers/stub_keystore/keystore_backend_definitions.h
- src/drivers/stub_keystore/stub_keystore.c
Update pfsoc_keystore with keystore_modif_key function
Update boards/ssrc submodules
> pfsoc_keystore atomic modify key function

- platforms/nuttx/src/px4/nxp/imx9/hrt/CMakeLists.txt
- platforms/nuttx/src/px4/nxp/imx9/hrt/hrt.c
> imx93: Add hrt driver

- platforms/nuttx/src/px4/nxp/imx9/include/px4_arch/micro_hal.h
- platforms/nuttx/src/px4/nxp/imx9/version/board_mcu_version.c
Read unique ID from OCOTP fuses.
> platforms/nuttx/src/px4/nxp: Add board identity

- ROMFS/px4fmu_common/init.d/airframes/4430_ssrc_strivermini
New striver mini airframe (4430)
> R12.1 striver mini af

- ROMFS/px4fmu_common/init.d/airframes/4421_ssrc_skywalker
- ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt
> R12.1 skywalker af

- platforms/nuttx/src/px4/microchip/mpfs/version/board_mcu_version.c
- src/systemcmds/ver/ver.cpp
This adds the FMU2 support to saluki-pi build
> Fmu2 support

- platforms/nuttx/src/px4/common/cpuload.cpp
Adds a hash function from process PID to store and find corresponding task info structure, instead of looping through the list.
This reduces complexity from O(n) to O(1) when calling sched_note_ functions, greatly reducing CPU load when there are a lot of processes and context switches.
> cpuload.cpp: Add PID hash function to find task structure

- ROMFS/px4fmu_common/init.d/airframes/50005_ssrc_scout_mini_rover
- ROMFS/px4fmu_common/init.d/airframes/50006_ssrc_bunker_rover
- ROMFS/px4fmu_common/init.d/airframes/50007_ssrc_bunker_mini_rover
Updated bunker mini number of cells and flight modes to all rovers
> updated bunker mini num of cells and flight modes to all rovers

- src/drivers/pwm_esc/pwm_esc.cpp
This adds support for iMX93 based FC, which has 2*6 PWMs on the FMU (on devices /dev/pwm0 and /dev/pwm1)
> Add more devices to pwm esc

- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
also fix the build output diagrams. There seems to be some change and "\n" doesn't anymore do new line, but have to use "\<br\>"
> update FPGA 4.16

- platforms/nuttx/src/px4/microchip/mpfs/px4io_serial/px4io_serial.cpp
- Ensure that all interrupts are masked when configuring the block
- Ensure that the RX serial shift register is empty after clearing FIFO as well as in buffer overflow situations
> mpfs/px4io_serial: Add more explicit resetting for the IP block

- src/drivers/uavcan/uavcan_drivers/socketcan/driver/src/socketcan.cpp
This enables CAN driver and UAVCAN for saluki-nxp93
It may also fix networking/mavlink and socketcan issues for mpfs due to NuttX fixes
> Enable can

- .gitmodules
- clone_public.sh
imx9 keystore submodule added
- Refactor ...
```
```
> Add imx9_keystore

- packaging/build_px4fw.sh
> Nxp signing

- platforms/nuttx/src/px4/common/usr_mcu_version.cpp
Enable flow control on uart 4 and 5, fix lpuart issues, fix crashing logger in kernel-mode
> Imx9 lpuart flowcontrol

- platforms/nuttx/src/px4/nxp/imx9/board_reset/board_reset.cpp
- platforms/nuttx/src/px4/nxp/imx9/include/px4_arch/device_info.h
> iMX93:add warm reset support

- src/systemcmds/netconfig/netconfig.cpp
Support commands to get local ip address and set/get the drip address
```
saluki> netconfig -h
Usage: netconfig <command> [arguments...]
Commands:
-h            Usage info
init          Initialize network
get_ipv4      Get current ipv4 address
set_drip      Get drip (gateway) address
<addr>      address as string (e.g. '192.168.0.1')
set_drip      Set drip (gateway) address
<addr>      address as string (e.g. '192.168.0.1')
```
Ip address get example:
```
saluki> set IPADDR `netconfig get_ipv4`
saluki> echo "ip: $IPADDR"
ip: 192.168.202.1
saluki> 
```
> systemcmd/netconfig: support arguments

- ROMFS/px4fmu_common/init.d/airframes/1404_ssrc_standard_vtol.hil
- ROMFS/px4fmu_common/init.d/airframes/1440_ssrc_skywalker_x8.hil
- ROMFS/px4fmu_common/init.d/airframes/CMakeLists.txt
- ROMFS/px4fmu_common/init.d/rc.hitl_testing
- Tools/simulation/gz/hitl_run.sh
- Tools/simulation/gz/models/ssrc_skywalker_x8/model_hitl.sdf
- src/modules/simulation/simulator_mavlink/sitl_targets_gz-sim.cmake
- test/mavsdk_tests/CMakeLists.txt
- test/mavsdk_tests/configs/hitl_gz_harm.json
- test/mavsdk_tests/configs/sitl_gz_harm.json
- test/mavsdk_tests/fw_mission.plan
- test/mavsdk_tests/mavsdk_test_runner.py
- test/mavsdk_tests/test_fw_mission.cpp
Pick a missing patch to 1.14.3 based px4
> Added support for hitl testing for vtol and fw

- Tools/simulation/gz/hitl_run.sh
- Tools/simulation/gz/models/ssrc_holybro_x500/model_hitl.sdf
- Tools/simulation/gz/models/ssrc_skywalker_x8/model_hitl.sdf
- Tools/simulation/gz/models/ssrc_standard_vtol/model_hitl.sdf
- Tools/simulation/gz/models/x500/model_hitl.sdf
- test/mavsdk_tests/mavsdk_preparing.cpp
- test/mavsdk_tests/mavsdk_test_runner.py
- test/mavsdk_tests/process_helper.py
Updated IPs of FC for model_hitl.sdf files in Tools/simulator/gz/models
Adjust delays for improved reliability for MAVSDK testing
Tested with HITL for mc, fw and vtol
> Update IPs of FC for model_hitl.sdf files in Tools/simulator/gz/models

- platforms/nuttx/src/px4/common/tasks.cpp
This updates the Nuttx and NuttX/Apps submodules to current tiiuae master.
There is an issue with imx9 which still needs to be resolved; the device doesn't boot when memorycard is inserted.
> Update nuttx submodule

- platforms/nuttx/src/px4/nxp/imx9/board_reset/board_reset.cpp
> nxp93: Do cold reset in reset type 2

- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
- .github/workflows/tiiuae-sitl-gzsim.yaml
- .github/workflows/tiiuae-sitl.yaml
build also sitl images as they are needed together with px4
> build on tags v1.14.[0-9]-*

- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
> Update FPGA to version 4.24.0

- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
To get SPI DMA fixes and MSS CAN support
> Update FPGA to v4.26.0 and bootloader to v2.6.0

- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
- Tools/generate_basic_build_info.sh
add link to nxp bootloader for px4 saluki_file_info.json.
This is ment for flashing tools to know what bootloader should be used.
> add saluki NXP bootloader link to saluki_file_info.json

- platforms/nuttx/src/px4/microchip/mpfs/hrt/hrt.c
As callout can access the hrt driver, it must be able to obtain the lock in order to do so.
> mpfs/hrt.c: Must release spinlock when callout is invoked

- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
I will update tag to v2.8.0 after testing..
> Update NXP bootloader to v2.8.0

- .gitmodules
- clone_public.sh
Integrate AssemblyAgent module into PX4-firmware. This PR does not yet enable building or starting the module from RC script, but just put in all the needed stuff.
> Assembly agent

- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
To get the latest NXP custom keys
> Update saluki-sec-scripts submodule

- platforms/common/include/px4_platform_common/log_history.h
- platforms/common/include/px4_platform_common/sem.h
- platforms/common/px4_work_queue/WorkQueue.cpp
- platforms/common/uORB/uORBDeviceNode.cpp
- platforms/common/uORB/uORBDeviceNode.hpp
- platforms/common/uORB/uORBManager.cpp
- platforms/common/work_queue/hrt_thread.c
- platforms/common/work_queue/work_thread.c
- platforms/nuttx/src/px4/common/px4_crypto.cpp
- platforms/nuttx/src/px4/common/usr_atomic.cpp
- src/drivers/px4io/px4io_serial.cpp
- src/drivers/uavcan/uavcan_drivers/socketcan/driver/src/thread.cpp
- src/lib/cdev/CDev.cpp
- src/lib/mixer_module/mixer_module.cpp
- src/modules/mavlink/mavlink_command_sender.cpp
- src/modules/mavlink/mavlink_ulog.cpp
- src/systemcmds/uorb/uORBDeviceMaster.cpp
This updates the NuttX submodule to take in all the latest semaphore optimizations
> Update nuttx w semaphore optimizations

- Tools/setup_rust.sh
Script to setup Rust compiler for local px4 build
> Add Tools/setup_rust.sh

- platforms/nuttx/src/px4/common/cpuload.cpp
- platforms/nuttx/src/px4/nxp/imx9/board_reset/board_reset.cpp
- platforms/nuttx/src/px4/nxp/imx9/hrt/hrt.c
- platforms/nuttx/src/px4/nxp/imx9/tone_alarm/ToneAlarmInterface.cpp
Fix the NXP/iMX.9 drivers in PX4 to work with SMP. Highlights are in commit messages.
Based on @tkaratapanis work, this needs ATF / TF-A
> imx9: Add SMP support to PX4

- platforms/nuttx/src/px4/common/cpuload.cpp
- platforms/nuttx/src/px4/nxp/imx9/board_reset/board_reset.cpp
This fixes multiple issues with SMP scheduling in NuttX, as well as with some watchdog, signal processing etc.
The NuttX updates are clean cherry-picks from upstream, and affect both MPFS and IMX93
There are also saluki-nxp93 fixes , which don't affect MPFS:
- Update ssrc/boards , only affect the nxp
- Updates for nxp93 warm reboot
- Update for PX4 cpuload driver, which corrects a race condition in SMP; doesn't affect MPFS due to different core boot sequence
> Update nuttx submodule for SMP scheduling fixes

- .github/workflows/tiiuae-pixhawk-and-saluki.yaml
Update bootloader for saluki-nxp93 support
> github actions/tiiuae: Update bootloader to v2.9.0 to support latest nxp93

- cmake/px4_add_module.cmake
Handle Rust dependencies with px4_add_module DEPENDS tag
Fix rust modules to use px4_add_module DEPENDS tag
Modify moi_agent to avoid fmt::Display trait which causes panic in Riscv kernel builds.
> Rust lib deps as interface

- platforms/nuttx/CMakeLists.txt
- platforms/nuttx/cmake/px4_impl_os.cmake
This PR enables static linking of all the "default" build apps as fully linked executables
> Enable static application linking

- platforms/nuttx/src/px4/nxp/imx9/board_reset/board_reset.cpp
Fix https://jira.tii.ae/browse/SSRCDP-11552
> Imx9 fix board reset
